### ISSUE TITLE
Syntax highlight not working is \n before :

### ISSUE THREAD

**Issue by millergarym** [mike-lischke/vscode-antlr4#1]
See attached images

![screen shot 2017-04-03 at 2 07 41 pm](https://cloud.githubusercontent.com/assets/769330/24595140/079fe708-1877-11e7-8928-61e1c10780a8.png)
![screen shot 2017-04-03 at 2 07 57 pm](https://cloud.githubusercontent.com/assets/769330/24595141/09c2c83e-1877-11e7-9c7f-cac5b3eb7069.png)

**Comment by mike-lischke** [comment]
Yes, this is a problem of the (mostly) line based matching in vscode. I have already a workaround for this but until this is publish you should place the colon on the same line as the rule name.

**Comment by millergarym** [comment]
Thanks for the reply.
I've taken to using
```
ruleName :
    alt1
  | alt2
;
```

**Comment by mike-lischke** [comment]
Fixed by [9e37f0c]
