### ISSUE TITLE
How to display graphs?

### ISSUE THREAD

**Issue by nimabrn** [mike-lischke/vscode-antlr4#10]
I’ve created a .g file which contains grammar rules but I don’t know how to parse input file and  display graphs.
I would be really great full if you could you help me.

**Comment by mike-lischke** [comment]
Which graphs would you like to see?

**Comment by nimabrn** [comment]
Is it possible to see parse tree?

**Comment by mike-lischke** [comment]
Not yet. That requires to get the parser interpreter to work (which is one of the next things I have on my radar).
