### ISSUE TITLE
VS Code crashes when debugging nested rules

### ISSUE THREAD

**Issue by Husan** [mike-lischke/vscode-antlr4#100]
VS Code is crashing on my Win8 machine when debugging an ANTLR parse tree.

This extension is incredible, and I love using it. Any help trying to understand or resolve this issue would be greatly appreciated.
[Code__PID__80__Date__12_11_2019__Time_07_16_24PM__302__Log.txt](https://github.com/mike-lischke/vscode-antlr4/files/3950782/Code__PID__80__Date__12_11_2019__Time_07_16_24PM__302__Log.txt)
[Code__PID__972__Date__12_11_2019__Time_07_16_24PM__348__Log.txt](https://github.com/mike-lischke/vscode-antlr4/files/3950783/Code__PID__972__Date__12_11_2019__Time_07_16_24PM__348__Log.txt)
[Code__PID__980__Date__12_11_2019__Time_07_17_06PM__218__Log.txt](https://github.com/mike-lischke/vscode-antlr4/files/3950784/Code__PID__980__Date__12_11_2019__Time_07_17_06PM__218__Log.txt)
[Code__PID__1896__Date__12_11_2019__Time_07_16_24PM__494__Log.txt](https://github.com/mike-lischke/vscode-antlr4/files/3950785/Code__PID__1896__Date__12_11_2019__Time_07_16_24PM__494__Log.txt)
[Code__PID__3008__Date__12_11_2019__Time_07_16_24PM__561__Log.txt](https://github.com/mike-lischke/vscode-antlr4/files/3950786/Code__PID__3008__Date__12_11_2019__Time_07_16_24PM__561__Log.txt)
[Code__PID__3136__Date__12_11_2019__Time_07_16_24PM__797__Log.txt](https://github.com/mike-lischke/vscode-antlr4/files/3950788/Code__PID__3136__Date__12_11_2019__Time_07_16_24PM__797__Log.txt)
[Code__PID__5144__Date__12_11_2019__Time_07_16_24PM__858__Log.txt](https://github.com/mike-lischke/vscode-antlr4/files/3950789/Code__PID__5144__Date__12_11_2019__Time_07_16_24PM__858__Log.txt)
[Code__PID__5656__Date__12_11_2019__Time_07_16_25PM__294__Log.txt](https://github.com/mike-lischke/vscode-antlr4/files/3950790/Code__PID__5656__Date__12_11_2019__Time_07_16_25PM__294__Log.txt)
[Code__PID__7220__Date__12_11_2019__Time_07_16_25PM__343__Log.txt](https://github.com/mike-lischke/vscode-antlr4/files/3950791/Code__PID__7220__Date__12_11_2019__Time_07_16_25PM__343__Log.txt)
[Code__PID__8416__Date__12_11_2019__Time_07_17_10PM__228__Log.txt](https://github.com/mike-lischke/vscode-antlr4/files/3950792/Code__PID__8416__Date__12_11_2019__Time_07_17_10PM__228__Log.txt)
[Code__PID__8532__Date__12_11_2019__Time_07_16_52PM__181__Log.txt](https://github.com/mike-lischke/vscode-antlr4/files/3950793/Code__PID__8532__Date__12_11_2019__Time_07_16_52PM__181__Log.txt)
[Code__PID__8684__Date__12_11_2019__Time_07_17_03PM__206__Log.txt](https://github.com/mike-lischke/vscode-antlr4/files/3950794/Code__PID__8684__Date__12_11_2019__Time_07_17_03PM__206__Log.txt)
[Code__PID__8908__Date__12_11_2019__Time_07_17_10PM__283__Log.txt](https://github.com/mike-lischke/vscode-antlr4/files/3950795/Code__PID__8908__Date__12_11_2019__Time_07_17_10PM__283__Log.txt)

**Comment by mike-lischke** [comment]
#99
