### ISSUE TITLE
Question: Backtracking

### ISSUE THREAD

**Issue by jan-johansson-mr** [mike-lischke/vscode-antlr4#102]
Hello,

I've got a simple grammar with some rule that needs backtracking to be resolved. e.g. a reserved word that can be used in two different contexts, say `id = 1` means what is stated, while `id: 1` means something else.

A construct can be:

```
rules:
  token '=' value,
  | token ':' bookmark
```

Let the sample text be `id: 1`, and with the parser running it hits the `token '=' value`, and then gets derailed because it expected `id = 1`. Is the debugger running the parser in the simpler `SLL` mode or in the more expensive mode of `LL(*)`?

Or maybe ANTLR4 doesn't do backtracking (that ANTLR3 did).

Best

**Comment by mike-lischke** [comment]
Jan, I fail to see the connection to the vscode extension here. Instead that seems to be a general ANTLR question, which you should rather ask on Stackoverflow.
