### ISSUE TITLE
Debug against multiple input files (list support for input)

### ISSUE THREAD

**Issue by joelmo** [mike-lischke/vscode-antlr4#103]
When debugging, I have lots of statements i want to test against. Having all these in same file is not pratical. I want to be able to choose multiple files and have the debugger console show errors for the first file that fails to parse.

**Comment by mike-lischke** [comment]
Is this really a question about debugging? Or is this rather about testing? It's not possible to debug more than a single parser instance at a time and you cannot have more than a single string as input.

For testing it would make sense of course to test against a set of files containing various content (for instance multiple C++ or Typescript files). So, I take this feature request as an idea to create a new feature to automatically test a grammar against files matched against a glob pattern.
