### ISSUE TITLE
Allow specifying jar path

### ISSUE THREAD

**Issue by RobertBaruch** [mike-lischke/vscode-antlr4#106]
X/Y problem: On Windows 10, I've set `CLASSPATH=.;F:\mystuff\antlr-4.8-complete.jar` in the system variables. But it seems that 4.7.1 is hardcoded into the extension because the lexer keeps getting generated with the line `self.checkVersion("4.7.1")` (at least for the python target).

This could be solved with a setting to either:
* Use the default provided with the extension
* Use whatever is on the CLASSPATH
* Use a specific jar file

**Comment by mike-lischke** [comment]
This has already been added in b0f7ebd. It's waiting for the next release.
