### ISSUE TITLE
Antlr4 grammar grammar in VS Code

### ISSUE THREAD

**Issue by ya-alexander** [mike-lischke/vscode-antlr4#107]
Hi,

I have used VS Code to create various grammars, everything working like a charm. However, I cannot get the Antlr4 grammar from [Antlr4 grammar](https://github.com/mike-lischke/vscode-antlr4/tree/master/grammars) to work in VS Code. I am sure I am missing something obvious. 

The grammar I want to parse:

```
grammar Hello;
r   : 'hello' ID;
ID  : [a-z]+ ;
WS  : [ \t\r\n]+ -> skip ;
```

The error I get when debugging the grammar in VS Code:

```
Lexer error (1, 1): token recognition error at: 'g'
<unknown>:1
Lexer error (1, 2): token recognition error at: 'r'
<unknown>:1
Lexer error (1, 3): token recognition error at: 'a'
<unknown>:1
Lexer error (1, 4): token recognition error at: 'm'
<unknown>:1
Lexer error (1, 5): token recognition error at: 'm'
<unknown>:1
Lexer error (1, 6): token recognition error at: 'a'
<unknown>:1
Lexer error (1, 7): token recognition error at: 'r'
<unknown>:1
Lexer error (1, 8): token recognition error at: ' '
<unknown>:1
Lexer error (1, 9): token recognition error at: 'H'
<unknown>:1
Lexer error (1, 10): token recognition error at: 'e'
<unknown>:1
Lexer error (1, 11): token recognition error at: 'l'
...
```

My configuration:

Antlr4
> Version: antlr-4.8-complete.jar

VS Code
> Version: 1.43.2 (user setup)
> Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
> Date: 2020-03-24T07:38:38.248Z
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363

ANTLR4 grammar syntax support
> Version: 2.2.3

ANTLR4 grammar syntax support settings
```
    "antlr4.generation":{
        "mode": "external",
        "language": "CSharp",
        "listeners": true,
        "visitors": true,
        "outputDir": "parser"
    }
```

ANTLR4 grammar syntax support lauch config
```
        {
            "name": "Antlr grammar",
            "type": "antlr-debug",
            "request": "launch",
            "input": "src/playground/Antlr/AntlrGrammar/Hello.txt",
            "grammar": "src/playground/Antlr/AntlrGrammar/ANTLRv4Parser.g4",
            "startRule": "grammarSpec",
            "printParseTree": true,
            "visualParseTree": true
        }
```

I also went through the issues [here](https://github.com/antlr/grammars-v4/issues?q=label%3Aantlr4+label%3Atarget%3Acsharp-standard+) but none of them quite fixed my problem. 

Is there a sample of how to use the Antlr4 grammar grammar in VS Code? 

Many thanks in advance,
Alex

**Comment by mike-lischke** [comment]
Could be it has to do with the fact that the ANTLR4 lexer needs an adaptor, which the extension cannot emulate using the interpreter. See [this code](https://github.com/mike-lischke/vscode-antlr4/blob/master/src/parser/LexerAdaptor.ts) for what I had to write for the extension to be able to parse ANTLR4 grammars.

**Comment by ya-alexander** [comment]
Hi,

Thanks for your quick response. I will have a look into it.

Kind regards,
Alex
