### ISSUE TITLE
Debugger crashes on Windows with vscode > 1.39.2

### ISSUE THREAD

**Issue by obiwanjacobi** [mike-lischke/vscode-antlr4#109]
![image](https://user-images.githubusercontent.com/3882444/80276667-7e709c80-86ea-11ea-9021-b527c4d6cc6a.png)

Something changed and now it crashes. It happens at the moment the debug graph view is about to be shown...

Not sure where to look for more info. Tried the extension log files but there's not much there.

**Comment by Ramshackle-Jamathon** [comment]
I'm also running into this on macos, but it only happens when `visualParseTree` is enabled.

vscode-antlr4: `v2.2.3`

VS-Code
```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z (1 wk ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

**Comment by obiwanjacobi** [comment]
I guess crashes don't have priority?

**Comment by mike-lischke** [comment]
I see a crash when I start debugging now, which has to do with a change in the underlying ANTLR4 TS runtime and I have fixed that.

However, this has nothing to do with the visual parse tree, though I have to investigate further.

**Comment by mike-lischke** [comment]
I uploaded a new version of the extension. Can you check if that solves your issue?

**Comment by obiwanjacobi** [comment]
VS-Code 1.46.1 with extension 2.2.4 works for me. Awesome!
Thanks Mike!

**Comment by mike-lischke** [comment]
Great to hear that, thanks.
