### ISSUE TITLE
Default debugging not available.

### ISSUE THREAD

**Issue by flowchartsman** [mike-lischke/vscode-antlr4#111]
VSCode Version Version: 1.45.1
OS: MacOS Mojave (10.4.6)

I am unable to debug my grammar. I have a relatively simple grammar file (`FQL.g4`) that I am editing and have debugged from the command line. When I save it in VSCode, java parser and lexer appear to be generated correctly in the `.antlr` directory, but there is no option to debug, and selecting the debugger from the sidebar prompts me to `open a file which can be debugged or run`.  The impression I got from reading the documentation was that this would "just work", so I'm confused. Attempting to `create a launch.json file` does not provide any environmental options related to ANTLR at all. Am I doing something wrong?

**Comment by flowchartsman** [comment]
![antlr_nodebug](https://user-images.githubusercontent.com/926884/83527810-47926100-a4b6-11ea-8ad8-2a74f864526d.gif)

**Comment by flowchartsman** [comment]
I have attempted to fix this myself, but there must be some secret sauce missing from the way I'm trying to build and debug the extension, because it's just not working.  I ran `npm install` then `tsc -p .`, which seemed to generate the proper code in the `out` directory, then opened code in the checkout of the extension.

I started by opening vscode in a directory that had a grammar and an `input.txt`. When running in debug mode, the ANTLR-specific sidebar was completely empty.

I was able to reactivate the option to debug by adding the `languages` object into package.json:

```
        "debuggers": [
            {
                "type": "antlr-debug",
                "label": "ANTLR4 Debug",
                "runtime": "node",
+                "languages": [
+                    "antlr"
+                ],
                "configurationAttributes": {
                    "launch": {
```

But it still does nothing, nor is there any logging anywhere or any indication of a problem. It just silently does nothing. I'll continue to plug away at it.

**Comment by flowchartsman** [comment]
Okay, so I was able to get debugging working by creating my own launch.json using the one [here](https://soft-gems.net/antlr4-extension-for-vscode-1-3-0-now-with-debugging-support/) as a template. I still think this could be a bit saner and could provide a default debugging session, but I will update the title of the issue to reflect this. Feel free to close or leave open and I'll see what I can do about offering up a patch.

**Comment by mike-lischke** [comment]
The debugger should indeed run out of the box, provided you have a launch config that gives the necessary info. If you don't specify a grammar path then the current editor would be used (provided it contains an ANTLR4 grammar).

**Comment by flowchartsman** [comment]
Thanks, I figured it out. If I can find a way to smooth it out some or offer other improvements, I'll just submit a PR, but thanks for humoring me :)
