### ISSUE TITLE
Environment Variables are not Expanded

### ISSUE THREAD

**Issue by srw** [mike-lischke/vscode-antlr4#112]
If I set the outputDir to ${workspaceFolder}/python it creates a ${workspaceFolder} folder instead of expanding it to the workspace folder as specified in https://code.visualstudio.com/docs/editor/variables-reference

**Comment by mike-lischke** [comment]
Can you give me the full configuration you used, so that I can see where you specified the path?

**Comment by mike-lischke** [comment]
According to https://code.visualstudio.com/docs/editor/variables-reference it seems there's no way to get a variable value programmatically.

**Comment by TyrsDev** [comment]
@mike-lischke I've been struggling with the same issue of wanting to include a .jar file (4.12 version) in the repository and having the "alternativeJar" path be relative to the project, is there any way for the "alternativeJar" path to resolve a relative path if the value is not an absolute path? For example "lib/antlr-4.12.0-complete.jar"? After all, I don't have to set an absolute path for the outputDir, which can just be a folder name. If we can't expand the "${workspaceFolder}" variable from the settings.json path, can't we at least allow relative paths?
