### ISSUE TITLE
Parser regeneration does not work on grammar save

### ISSUE THREAD

**Issue by lamest** [mike-lischke/vscode-antlr4#115]
It works after VS restart, but only the first time you save a change.

**Comment by wonrax** [comment]
I'm also having this problem. Did you manage to find a workaround?

**Comment by wonrax** [comment]
Did you use vscode predefined variables like **${workspaceFolder}** in **launch.json**? I was having this problem too but I changed the grammar path to relative to my workspace and it worked.

"Paths are resolved relative to your workspace."
https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/grammar-debugging.md#Setup

**Comment by lamest** [comment]
I use Idea now as its seems more convinient for me right now. Cant actually check the issue so will close it for now.
