### ISSUE TITLE
Generated class references

### ISSUE THREAD

**Issue by cobolcowboy** [mike-lischke/vscode-antlr4#116]
I'm trying to get VSCode to stop complaining about not being able to find the generated classes from antlr. I added the antlr output folder to my Java referenced libraries but it doesn't seem to pick that up, so anywhere in my source that references those classes appears to be an error. The project will build fine but this is annoying. I did search around SO and others and saw a few other people asking but no answers. Perhaps this is just something I have to live with? Apologies if this is a noob Java issue...I don't work with it much and wasn't sure where else to ask. Thanks for any input.

EDIT: The folder is included in my .classpath

**Comment by mike-lischke** [comment]
I'm afraid this is not a problem caused by the ANTLR4 extension, but has something to do with your project setup (maybe build path configuration or similar, I'm no Java expert).
