### ISSUE TITLE
Cannot implement semantic predicates via actionFile hack

### ISSUE THREAD

**Issue by danielgesua** [mike-lischke/vscode-antlr4#117]
Hi Mike,

I'm having problems getting semantic predicates to work and I wonder if you'd be able to help me. I'm following the process in this "Grammar Debugging" doc:

https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/grammar-debugging.md

To be honest I have zero Javascript experience. I copy-pasted the example's code into a JS file on the root, properly added the filename to the "actionFile" field of the launch.json, tried running the debugger, and got an error saying:

"Could not prepare debug session:
ReferenceError: module is not defined"

Then I tried converting the code to ES6 using VSCode's automatic conversion feature, and that gave me:

"Could not prepare debug session:
SyntaxError: Unexpected token 'export'"

Then I figured maybe it was cause I didn't have NodeJS installed on this workstation so I tried installing and adding the path to PATH in my environment variables. No luck, same errors.

I tried all the above with both the "PredicateEvaluator" snippet and the "standalone function" snippet and still couldn't get it.

I pray you can help me determine what kind of silly non-sense I'm doing wrong hahaha.

Without predicates, I wouldn't be able to apply the true power of Antlr4 and this extension has been a game changer thanks to it's amazing graphical representations.

For reference, I'm running a windows 10 computer, the extension's version is 2.2.4.

Thanks for making such an amazing application. I can't wait to see it develop.

Best,

Daniel Gesua

**Comment by serras** [comment]
I am having the same problem. Did you have any luck solving it?

**Comment by danielgesua** [comment]
No. We switched to a different lexer/parser.

**Comment by serras** [comment]
I managed to get it working! It seems that you need to _return_ the object instead of exporting it:

```js
({
  evaluateLexerPredicate: (lexer, ruleIndex, actionIndex, predicate) => eval(predicate),
  evaluateParserPredicate: (parser, ruleIndex, actionIndex, predicate) => eval(predicate)
})
```
