### ISSUE TITLE
Changing Formatting Syntax or add a convention specifier

### ISSUE THREAD

**Issue by Marti2203** [mike-lischke/vscode-antlr4#118]
Hello,
I constantly use the extension but the formater is not sometimes conventional - a semicolon is preferred to be on a new line and the rule for groupings which are big is a little janky. Is it possible to add configuration settings for these things or a way to specify how to format?

**Comment by mike-lischke** [comment]
Does this document help you here: https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/formatting.md?

**Comment by Marti2203** [comment]
Oh, nice! Yes, I am gonna see what I can do with them, can I add more configurations by doing a PR?

**Comment by mike-lischke** [comment]
Absolutely! Just see that you keep the same code style and you sign the contributor.txt file.
