### ISSUE TITLE
Can I add an option to clear the log on success?

### ISSUE THREAD

**Issue by SQLGate** [mike-lischke/vscode-antlr4#122]
If there is a problem while working, an error code is displayed in the ANTLR Exception output window.

However, if there are no problems, I can't tell if it was successful because an error log was left before.

Can I add an option to clear the log on success?

**Comment by mike-lischke** [comment]
I assume you mean the "ANTLR4 Errors" channel in the OUTPUT tab. What would you consider to be a good opportunity to clear it? When a grammar is saved? Or when a debug session starts?
