### ISSUE TITLE
Token visualisation 

### ISSUE THREAD

**Issue by gkjpettet** [mike-lischke/vscode-antlr4#123]
Hi,

Many thanks for this extension - it’s proving really useful when learning ANTLR. 

Does the extension provide any way to see the tokens generated during lexing? I have figured out how to view the parse tree from an input text file but I would really like to see the tokens generated before parsing. 

Is this possible?

**Comment by mike-lischke** [comment]
Yes, there are 2 visualizations of the recognized tokens. One is in the textual parse output. The list is printed right before the tree.

The other place is the debug variables view. Once you [started debugging](https://github.com/mike-lischke/vscode-antlr4/blob/master/images/live-parse-tree.gif) a grammar and stopped at a breakpoint you will see the list of yet consumable tokens in the debugger variables view.

**Comment by gkjpettet** [comment]
Ah. I’ve managed to find them in the debugger view - thank you. 

I don’t seem to be able to see them beside the parse tree however.

**Comment by mike-lischke** [comment]
The token list is printed right before the textual parse tree, after a parse run ended:

<img width="1146" alt="Bildschirmfoto 2020-10-30 um 09 39 54" src="https://user-images.githubusercontent.com/2398704/97678346-f651c200-1a93-11eb-94ec-4d27b3da65b7.png">

But it must be enabled in the [launch config](https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/grammar-debugging.md#setup) (active if not specified).

**Comment by gkjpettet** [comment]
Thank you @mike-lischke. I just needed to add `"printParseTree": true` to my `launch.json` file and it worked!
