### ISSUE TITLE
Publish extension on open-vsx.org, so it can be used in VSCodium, Gitpod

### ISSUE THREAD

**Issue by geekley** [mike-lischke/vscode-antlr4#124]
Can you please publish the extension on [open-vsx.org](https://open-vsx.org), so it can reach more users?
Open-VSX is a vendor-neutral alternative to VS Marketplace, [that can legally be used](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace) in VS Code forks like [VSCodium](https://github.com/VSCodium/vscodium#why-does-this-exist), [GitPod](https://www.gitpod.io/features/#vs).
Of course, you don't have to change anything in the extension itself.

[The process](https://github.com/eclipse/openvsx/blob/master/cli/README.md) is pretty much the same as publishing to VS Marketplace.
It can even be automated, see [this repo](https://github.com/open-vsx/publish-extensions#publish-extensions-to-open-vsx):
> Though the preferred solution for such a situation is to convince the maintainers to start publishing themselves, you can add the extensions here to have them published by our CI workflow.

You can [claim ownership](https://github.com/eclipse/openvsx/wiki/Namespace-Access) of your namespace `mike-lischke`, and officially support the extension there.

More details on [this blog post](https://www.gitpod.io/blog/open-vsx/).

**Comment by mike-lischke** [comment]
I see no motivation to support open-vsx.org currently. Maybe at a later point in time.
