### ISSUE TITLE
VSCode Debugger Not Working?

### ISSUE THREAD

**Issue by sambonfire** [mike-lischke/vscode-antlr4#125]
I'm using v2.2.4 of the plugin on VSCode version 1.52.1.  Everything seems to be working for the plugin, but I have no option to debug the grammar.  When I select "Start Debugging" my only options are:

![image](https://user-images.githubusercontent.com/26911387/103821173-8414d500-5022-11eb-89dc-a160cae3fb4f.png)

Am I missing something or doing something wrong?  I was following along with the instructions about how to debug but am not sure where to go from here..

**Comment by wisemandenny** [comment]
You need to add a new configuration in your launch.json

**Comment by mike-lischke** [comment]
You need the debugger key to add a new launch task. No idea why there is no entry for vscode-antrl4. Is the extension actually installed and activated?

**Comment by wisemandenny** [comment]
I just picked a random option from the list in the screenshot above, and then overwrote it with the launch.json included in the debuggng manual for this plugin. Then it worked.

**Comment by mike-lischke** [comment]
This is how it looks for me with the extension installed from the marketplace (not a debug version):

<img width="889" alt="antlr-debug" src="https://user-images.githubusercontent.com/2398704/106354396-d7143c00-62f1-11eb-81b1-60bfd6bebfbd.png">

**Comment by whisper-bye** [comment]
my semantic predicates is not working...

**Comment by xpe** [comment]
@whisper-bye Re: "my semantic predicates is not working..." ... First of all, is your problem related to this particular GitHub Issue? If not, would you please file a separate ticket? If it is related to this one, please provide more information here. Thank you.

**Comment by marekwn** [comment]
I am facing same issue - no debugger key. Could you please provide some help how to add it manually?
I've tried a few times to install/uninstall the extension but no luck. The extension itself works, i have java code generated on save, but cannot run debugger :(

**Comment by mike-lischke** [comment]
Actually, I have no idea what could be wrong. There's no way to add a launch configuration snippet by a user. It's defined in [package.json](https://github.com/mike-lischke/vscode-antlr4/blob/master/package.json#L530). But you can add a launch configuration without the snippets. Just fill your `.vscode/launch.json` with something like this:

```json
{
    "version": "2.0.0",
    "configurations": [
        {
            "name": "Current Grammar",
            "type": "antlr-debug",
            "request": "launch",
            "grammar": "${file}",
            "actionFile": "grammars/exampleActions.js",
            "input": "input.txt",
            "startRule": "start",
            "printParseTree": true,
            "visualParseTree": false
        }
    ]
}
```

After that you should see an entry like this:

![Bildschirmfoto 2022-04-23 um 18 56 17](https://user-images.githubusercontent.com/2398704/164915898-2fcc2503-0fb9-4504-85ec-d443a1bb4986.png)
