### ISSUE TITLE
Automatic generated lexer has compilation error

### ISSUE THREAD

**Issue by cnayan** [mike-lischke/vscode-antlr4#126]
Hi,

When I save my lexer g4 file, this is the top section in generated.

```javascript
var antlr4 = require('antlr4/index');
```

When I import the lexer file,

`import { MyLexer } from '../.antlr/MyLexer';`

I see this error:

```
 ERROR  Failed to compile with 1 error                      
                                                            
This dependency was not found:                              
                                                            
* antlr4/index in ./src/language/antlr/.antlr/MyLexer.js  
                                                            
To install it, you can run: npm install --save antlr4/index 
```

If I manually change `var antlr4 = require('antlr4/index');` to `var antlr4 = require('antlr4');` the compilation succeeds.

What am I missing to resolve this problem without manual change?

Thanks!

**Comment by cnayan** [comment]
The import statements are correctly generated via JAR file execution. Same goes for IntelliJ plugin.
This problem seems to be VS Code plugin only.

**Comment by mike-lischke** [comment]
Looks like the import statement you mentioned first is generated by the ANTLR4 tool (JS target?). So it's not a problem of this extension.
