### ISSUE TITLE
Question about charPositionInLine field in token

### ISSUE THREAD

**Issue by Ketler13** [mike-lischke/vscode-antlr4#127]
Hi Mike, I'm trying to use your approach from the https://stackoverflow.com/questions/59041584/determining-context-at-a-position-in-file-using-antlr4.
The only problem that I can't figure out why in my case I don't have that field charPositionInLine in both symbol and start/stop. Please, take a look at the screenshots below.
My antlr version is 4.9.1.
![image](https://user-images.githubusercontent.com/24254801/105022868-ea521c80-5a52-11eb-83ff-b9f9099fab47.png)
![image](https://user-images.githubusercontent.com/24254801/105022879-ecb47680-5a52-11eb-9765-447a70b7b864.png)

**Comment by mike-lischke** [comment]
Some targets use a different naming for fields. I assume here you should use column instead.

**Comment by Ketler13** [comment]
Thank you a lot
