### ISSUE TITLE
'module is not defined' trying to add an action file for debugging

### ISSUE THREAD

**Issue by obiwanjacobi** [mike-lischke/vscode-antlr4#129]
I am trying out predicates -currently two simple boolean flags.
I have my TS code compiling (using mixins) and was trying to get debugging working using https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/grammar-debugging.md.

Here is my action file (copied from the example in previous link):
```
"use strict"

// GrammarProfile interface
var directiveDot = true;
var directiveDotOptional = false;

module.exports.evaluateLexerPredicate =
    function (lexer, ruleIndex, predicateIndex, predicate) {
        return eval(predicate);
    }

module.exports.evaluateParserPredicate =
    function (parser, ruleIndex, predicateIndex, predicate) {
        return eval(predicate);
    }
```

When I try to run the debugger on a simple test expression that triggers my conditional parser rule, I get an error saying:
```
Could not prepare debug session:

ReferenceError: module is not defined
```

... Help. ;-)

**Comment by mike-lischke** [comment]
Meanwhile I have changed this part, so that it is no longer necessary to export anything or write evaluators. However that change is not yet published. No idea how you could update an installed extension with fresh source code, but if you can you would probably have this issue solved. Otherwise you probably have to wait for the next release (which I cannot promise when this will be).

**Comment by ThinCats** [comment]
workaround by https://github.com/mike-lischke/vscode-antlr4/issues/117#issuecomment-711800100 in current version (2.2.4)

```js
(function () {
  // GrammarProfile interface
  var directiveDot = true;
  var directiveDotOptional = false;

  return ({
    evaluateLexerPredicate: (lexer, ruleIndex, actionIndex, predicate) => eval(predicate),
    evaluateParserPredicate: (parser, ruleIndex, actionIndex, predicate) => eval(predicate)
  })
})()
```

**Comment by mike-lischke** [comment]
The debugging setup with action files has changed since this issue was reported. So I wonder if it still applies or we can close it?
