### ISSUE TITLE
Add debug output for the extension in vscode

### ISSUE THREAD

**Issue by EternalPhane** [mike-lischke/vscode-antlr4#13]
When dealing with separate lexer and parser grammar, tokens added to lexer file __after `tokenVocab` in parser file is specified__ will cause "Unknown token reference" error, even after regeneration (clean .antlr folder and save lexer/parser files again, or manually call antlr4 from terminal, anyway).

**Comment by EternalPhane** [comment]
To reproduce:
1. Create new file `A.g4` and save:
```antlr
parser grammar A
;

options
{
    tokenVocab = ALexer;
}

a
    : A
;
```
2. Create new file `ALexer.g4` and save:
```antlr
lexer grammar ALexer
;

A
    : 'a'
;

B
    : 'b'
;
```

Result:

![image](https://user-images.githubusercontent.com/11267872/33797818-795b3cde-dd49-11e7-955a-898b3e600c9f.png)

**Comment by EternalPhane** [comment]
Currently I have to cut the `tokenVocab` line - save - paste - save to force the extension to recognize the new tokens.

**Comment by mike-lischke** [comment]
Any change in your parser grammar updates the symbol table, even just pressing space.

**Comment by EternalPhane** [comment]
Well, I made a mistake in the reproduction steps...

1. Create a new file `A.g4` and save:
```antlr
parser grammar A
;

options
{
    tokenVocab = ALexer;
}

a
    : A
;
```
2. Create a new file `ALexer.g4` and save:
```antlr
lexer grammar ALexer
;

A
    : 'a'
;
```
Now press space and `A` is recognized.

3. Add the following to `ALexer.g4` and save:
```antlr
B
    : 'b'
;
```
4. Add the following to `A.g4` and save:
```antlr
b
    : B
;
```
Now the issue is right there.

**Comment by EternalPhane** [comment]
Reopening the parser file can let the new tokens recognized, but I would appreciate it if you could make it work as soon as the lexer file is modified and saved. Maybe add a hook or something?

**Comment by mike-lischke** [comment]
Weird. When I add a new lexer symbol in the lexer grammar it is immediately available in the parser grammar. No error marker appears and the symbol info is available. I don't even need to save either file. I tried this also with a fairly complex grammar, which takes a moment to analyze. Still, everything is immediately there. What else could cause your trouble?

**Comment by EternalPhane** [comment]
My configuration:
```js
{
    "antlr4.format.alignColons": "hanging",
    //"antlr4.format.alignLexerCommands": true,
    "antlr4.format.alignSemicolons": "ownLine",
    //"antlr4.format.allowShortBlocksOnASingleLine": false,
    "antlr4.format.allowShortRulesOnASingleLine": false,
    "antlr4.format.breakBeforeBraces": true,
    "antlr4.format.breakBeforeParens": true,
    "antlr4.format.columnLimit": 10000,
    "antlr4.format.minEmptyLines": 1,
    "antlr4.format.reflowComments": false,
    "antlr4.format.useTab": false,
    //"antlr4.referencesCodeLens.enabled": true,
}
```
VSC information:
```
版本 1.19.0-insider
提交 d8989c95964ce06c64ffebc2fb400a0327bd447d
日期 2017-12-08T10:45:40.870Z
Shell 1.7.9
渲染器 58.0.3029.110
Node 7.9.0
架构 x64
```

**Comment by EternalPhane** [comment]
Btw, could you please print some logs (output from antlr4, javac, etc.) in the output window? Of course users can clone the repo and debug the extension in vsc, but it may be better if they can check what's wrong without the need of it.

**Comment by mike-lischke** [comment]
Why did you add your formatter settings here? This issue is about unrecognized symbols.

> Btw, could you please print some logs (output from antlr4, javac, etc.) in the output window? Of course users can clone the repo and debug the extension in vsc, but it may be better if they can check what's wrong without the need of it.

What do you have in mind that should be printed?

**Comment by EternalPhane** [comment]
> Why did you add your formatter settings here? This issue is about unrecognized symbols.

I thought the settings may affect the behavior of the extension, however I've been aware that I was wrong.
> What do you have in mind that should be printed?

Emmm... Output from antlr4-graps maybe? I mean I don't quite understand the mechanism of this extension.

**Comment by mike-lischke** [comment]
I see, ok. So what about converting this issue into a FR for more debug output? I cannot reproduce the original issue. It seems to work well, as I described above.

**Comment by EternalPhane** [comment]
Fair enough. I'll reinstall vsc and disable other extensions to see if the issue will still persists.

**Comment by mike-lischke** [comment]
Thinking about this again, I come to the conclusion that there's nothing here I can do. Adding extra logging calls to the extension code is pretty odd. This is not how problems are handled in vscode extensions. Errors can be seen in the developer tools window and anything else is useless, since nobody is every going to read it.

Better ask specific questions if you need to understand certain processing in the extension.
