### ISSUE TITLE
CSharp file generation naming convention

### ISSUE THREAD

**Issue by romarro** [mike-lischke/vscode-antlr4#131]
Hi, I used the extension version 2.2.4 to generate CSharp lexer and parser for a toy grammar named "chat".
Naming the grammar file with first lower case, and also the grammar name with a lower case results in classes generated with lower case. For example:
chat.g4 (grammar chat) => chatLexer.cs,  chatParser.cs etc.

Chat.g4 (grammar Chat) => ChatLexer.cs, ChatParser.cs

I am using the VS code version:
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by mike-lischke** [comment]
I'm glad you use my extension. What's the problem you want to report?

Note: The extension has no influence on the generated code in any way. It uses external Java jars to do the generation.

**Comment by romarro** [comment]
As you can see in the image attached when I use a lower case grammar name all the generated C# files are with lower case. 
When I use Capital case the generated files are with Capital Case.
![Case generation](https://user-images.githubusercontent.com/7783693/106030782-2c283600-60d7-11eb-9643-9898e2c9e9b1.png)

Thinking now, it may be possible to be an issue with the Antlr4 generator and not specific to this extension.

**Comment by mike-lischke** [comment]
Right, that's not in my hands to fix.
