### ISSUE TITLE
Bug: alignColons formatting setting affects semicolon on first line

### ISSUE THREAD

**Issue by xpe** [mike-lischke/vscode-antlr4#134]
The `alignColons` [setting][ES], as I understand it, should only impact **colons** (`:`). However, I've noticed that it changes the formatting of **semi**colons (`;`) on the first line in both my parser grammar and lexer grammar.

For example, here is the result of formatting:

```g4
lexer grammar FooLexer
    ;
```

Just in case there might be some kind of interactions between settings, here are my settings:

```json
    "antlr4.format": {
        "alignTrailingComments": true,
        "allowShortBlocksOnASingleLine": true,
        "breakBeforeBraces": false,
        "columnLimit": 78,
        "continuationIndentWidth": 4,
        "indentWidth": 4,
        "keepEmptyLinesAtTheStartOfBlocks": false,
        "maxEmptyLinesToKeep": 1,
        "reflowComments": false,
        "spaceBeforeAssignmentOperators": true,
        "tabWidth": 4,
        "useTab": false,
        "alignColons": "hanging",
        "singleLineOverrulesHangingColon": true,
        "allowShortRulesOnASingleLine": true,
        "alignSemicolons": "hanging",
        "breakBeforeParens": false,
        "ruleInternalsOnSingleLine": false,
        "minEmptyLines": 1,
        "groupedAlignments": true,
        "alignFirstTokens": true,
        "alignLexerCommands": false,
        "alignActions": false,
        "alignLabels": true,
        "alignTrailers": false
    },
```

[ES]: https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/extension-settings.md

**Comment by mike-lischke** [comment]
You have set "alignSemicolons" to hanging as well. This is probably why you got this result.

**Comment by xpe** [comment]
> You have set "alignSemicolons" to hanging as well. This is probably why you got this result.

Do you agree with these statements:
* `alignSemicolons` should _only_ apply to rule definitions.
* `alignSemicolons` should _not_ apply to the first line of a grammar file (e.g. `lexer grammar` or `parser lexer`).

**Comment by xpe** [comment]
My goal is setup the extension to do ANTLR formatting along the lines of common examples provided in TDAR and many examples in the ANTLR grammars repo. This means:
* in rules, align `:`, `|`, and `;`
* use semicolons normally in non-rules (such as `lexer grammar FooGrammar`)

I don't think this is currently possible given the current setting options, which is why I filed this as a bug.

**Comment by mike-lischke** [comment]
> Do you agree with these statements:
> 
>     * `alignSemicolons` should _only_ apply to rule definitions.
> 
>     * `alignSemicolons` should _not_ apply to the first line of a grammar file (e.g. `grammar`, `lexer grammar`, or `parser grammar`).

I haven't thought about other occurences than rules, so I cannot answer with yes currently. However, I have not seen output where the semicolon from the introducer line is placed on the next line and I have tests with all 3 semicolon settings. But maybe I just missed that.

**Comment by mike-lischke** [comment]
> My goal is setup the extension to do ANTLR formatting along the lines of common examples provided in [TDAR](https://pragprog.com/titles/tpantlr2/the-definitive-antlr-4-reference/) and many examples in the [ANTLR4 grammars repo](https://github.com/antlr/grammars-v4). This means:
> 
>     * in rules, align `:`, `|`, and `;`
> 
>     * use semicolons normally in non-rules (such as `lexer grammar FooGrammar;`)

I agree. The setting should not affect non-rules.

> I don't think this is currently possible given the current setting options, which is why I filed this as a bug.

If that's the case then it should be fixed. Interesting here is that I never got a bug report for this issue, which either means people don't care about it or they never use hanging semicolons. I certainly do not.
