### ISSUE TITLE
Parse tree visualizer collapses whitespace

### ISSUE THREAD

**Issue by xpe** [mike-lischke/vscode-antlr4#135]
The parse tree visualization collapses adjacent whitespace.

For example. Given a rule matching this string (which includes quotes as part of the match): <pre>"a     b"</pre> (There are five spaces between `a` and `b`.) The parse tree visualization collapses the intermediate spaces and only shows `"a b"`.

I suspect this is an HTML rendering issue in the extension. By default, browsers collapse multiple spaces down to one in anything except a `<pre>` tag.

**Comment by xpe** [comment]
I'm chasing down some of the details.

The CSS for the SVG uses a monospace font, as expected. Here is the relevant rule from `dark.css`:

```
body.vscode-dark g .token-value {
    fill: white;
    stroke: none;
    font: 12pt "Source Code Pro", "Hack", "Consolas", "Andale Mono", monospace;
}
```

**Comment by xpe** [comment]
I just noticed this uses d3 for visualization. Here is some relevant code from `parse-tree.js`:

```js
    // The node's content if this it is a terminal.
    nodeText = nodeEnter.append("text")
        .attr("class", "token-value")
        .attr("x", 0)
        .attr("y", rectH / 2)
        .attr("dy", horizontal ? "0.25em" : "2.5em")
        .text(function (d) {
            if (d.data.type == 0) {
                return "";
            }

            if (d.data.type == 2) { // Error node.
                if (d.data.symbol.tokenIndex == -1) {
                    return "<missing>";
                }
                return "<unexpected: " + d.data.symbol.text + ">";
            }

            return d.data.symbol.text;
        });
```

**Comment by xpe** [comment]
I think this can be solve with only a CSS change. Add this:

```
white-space: pre;
```

More at https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by xpe** [comment]
I verified that this will work. Before I submit a patch request, I have a follow-up comment:

For an element with monospaced font, is there ever a case where you *don't* want the `white-space: pre` CSS rule?

My guess would be "no".

**Comment by mike-lischke** [comment]
Difficult to say which behavior would be more desirable, but this issue is the first about that matter, so I assume it's not of high interest, usually. Let's go with the change to prevent collapsing white spaces first and see if someone complains.
