### ISSUE TITLE
VS Code extension seems to be "generating interpreter data" endlessly

### ISSUE THREAD

**Issue by octogonz** [mike-lischke/vscode-antlr4#136]
## Repro steps
1. Start VS Code
2. Open an ANTLR grammar file (with `.g4` file extension)
3. Observe that the VS Code status bar looks normal
4. Save a change to the grammar file

**What happens**

The status bar shows an icon animation indicating that work is being performed:

![VS Code](https://user-images.githubusercontent.com/4673363/111923999-67077400-8a5f-11eb-9e0f-ad747405a72e.png)

This animation continues forever, even though no further changes are made to the editor, and the file has already been saved.

The animation continues even after all ANTLR files have been closed.

**What should happen**

After the `vscode-antlr4` extension completes its analysis, the animation should stop.

**Comment by Nicolaks** [comment]
Hey, I have the same error, ANTLR seems to spin endlessly without ever stopping.
 Does anyone have a solution for this bug?

**Comment by Nicolaks** [comment]
I found the solution, you just need to install Java (jre) on your computer, restart your computer and reinstall the extension and that's done.

**Comment by octogonz** [comment]
> You just need to install Java (jre) on your computer. 

Could we make this optional? The VS Code extension seems to work fine in this state. On my computer the JRE files are installed locally under the folder of the ANTLR tool. I do not want to install the JRE globally.

**Comment by mike-lischke** [comment]
You can switch off parser generation, even for internal purposes. The extension will then not launch a java process at all. See the mode setting in [extension settings](https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/extension-settings.md#parser-generation).
