### ISSUE TITLE
Extension fails to activate

### ISSUE THREAD

**Issue by CornCobs** [mike-lischke/vscode-antlr4#137]
The extension has been working for me previously. However recently the extension fails to start up. Looking at the VSCode developer console, there is a log:

![image](https://user-images.githubusercontent.com/28252911/112148786-4125cf00-8c19-11eb-9908-13656d518d9f.png)

Deleting and reinstalling the extension did not work.

**Comment by mike-lischke** [comment]
Not sure if that's the failure of the extension or vscode, but I'll take a look.

**Comment by mike-lischke** [comment]
A new release (2.4.0) was just published, which hopefully also fixes this issue.
