### ISSUE TITLE
Make output of the sentence generator more prominent

### ISSUE THREAD

**Issue by phdoerfler** [mike-lischke/vscode-antlr4#138]
# Act 1

I stumbled upon [this SO answer](https://stackoverflow.com/a/34352450/969122). Intrigued, I went on to look for that functionality. First in the command list (Cmd+Shift+P) to no avail. Later I learned (from the extensions readme) that it is the context menu where my search might find an end and indeed:
![image](https://user-images.githubusercontent.com/163428/112728214-79cded00-8f26-11eb-87e3-cb588873f2ab.png)

# Act 2
So I clicked it and... nothing happened™️. Looking through the docs was fruitless, I eventually used the source, Luke, and found the [SentenceGenerator](https://github.com/mike-lischke/vscode-antlr4/blob/master/src/backend/SentenceGenerator.ts) which, thanks to Githubs code analysis eventually brought me to the [extension.ts file](https://github.com/mike-lischke/vscode-antlr4/blob/807909388d9a61bdccb10f65ee399269e28ac487/src/extension.ts#L201) which spoke of a `sentenceOutputChannel`. This clued me into looking in the "logs" (I know they aren't, but, well, they _feel_ like logs) and lo and behold:
![image](https://user-images.githubusercontent.com/163428/112728371-417ade80-8f27-11eb-9375-a513615af8ad.png)

# Act 3
The code also speaks of `sentenceOutputChannel.show(true);` but I have never witnessed that happen. Never did that output channel cry for my attention. Experimentally, I tried pasting in the editor, suspecting that maybe the generated valid input was copied into the clipboard, but of course it was not.

# Addendum
It might very well be that `sentenceOutputChannel.show(true);` should have actually done something it didn't. I can but surmise that it would show the output channel and thus make it obvious where that input was generated. This would also lend to it not being documented anywhere (other than aforementioned SO answer). Or maybe it works as intended and I'm just daft and forgot about some arcane "Never pop output channels into my face unasked" setting I turned on ages ago, because there was always this one extension that just loved to do that.

**Comment by mike-lischke** [comment]
The described misbehavior is only because the sentence generation is not fully implemented. In fact I'm surprised the feature shows up in the context menu. I probably just forgot to remove the entry before publication.

In the TS code the channel is opened when output is generated (I just tested it again). But the call to reveal the channel in the UI is not yet part of the released code.

**Comment by phdoerfler** [comment]
I see, thanks for the clarification! I'm gonna wait patiently until it's fully implemented then :)
