### ISSUE TITLE
Can't figure out how to debug grammar file

### ISSUE THREAD

**Issue by thatbirdguythatuknownot** [mike-lischke/vscode-antlr4#139]
I've put in my grammar name in launch.json file and this error pops up:

>  Error: Debugger creation failed. You are either trying to debug an unsupported file type or no interpreter data has been generated yet for the given grammar.

the grammar is a .g4 file if you're asking

**Comment by Doomsdan** [comment]
how did you solve it?

**Comment by Marouns** [comment]
was it solved ? how ?
