### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by binhtran432k** [mike-lischke/vscode-antlr4#141]
- Issue Type: `Performance`
- Extension Name: `vscode-antlr4`
- Extension Version: `2.2.4`
- OS Version: `Linux x64 5.4.0-72-generic`
- VS Code version: `1.55.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/mike-lischke.vscode-antlr4-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[mike-lischke.vscode-antlr4-unresponsive.cpuprofile.txt](https://github.com/mike-lischke/vscode-antlr4/files/6328724/mike-lischke.vscode-antlr4-unresponsive.cpuprofile.txt)

**Comment by mike-lischke** [comment]
Which grammar have you been working on when this high CPU issue came up? Loading data from the generated parser files seems to cause the delay. You can switch that off (by disabling code generation), but will lose some functionality then (no debugging, most graphs).

**Comment by binhtran432k** [comment]
I am working on assignment of class. I fix the problem when remove or replace with default provided folder the .antlr4 folder in the same directory. So now I will close this issue.
