### ISSUE TITLE
No ATN data found - Code generation worked (c# target)

### ISSUE THREAD

**Issue by madf0x** [mike-lischke/vscode-antlr4#143]
I'm not able to get any ATN graph.
I've already read a closed issue about this, but wasn't able to solve it.

These are my settings:
![settings](https://user-images.githubusercontent.com/13233026/119150667-f248ba00-ba4e-11eb-88eb-14ac885d0f8a.PNG)

This is the output in the developer console:
![dev_con](https://user-images.githubusercontent.com/13233026/119150709-fe347c00-ba4e-11eb-9062-340f9e4da710.PNG)

The error at the end occurs, when I click into the ATN graph window after selecting a rule.

**Comment by mike-lischke** [comment]
From your screenshot I don't see any mention that ATN data could not be found. However, that warning about a problem accessing the grammar seems odd. Maybe it has to do with the problem you see?

**Comment by madf0x** [comment]
![no_atn_data_found](https://user-images.githubusercontent.com/13233026/120183632-3c305d80-c210-11eb-8526-ecd6c0e0642b.PNG)

I didn't think that this screenshot would help, that's why I skipped it.

**Comment by mike-lischke** [comment]
Have you tested that recently? Might be fixed in a newer release of the extension.
