### ISSUE TITLE
antlr4.generation.outputDir doesn't seem to be working

### ISSUE THREAD

**Issue by nik9000** [mike-lischke/vscode-antlr4#15]
I'm trying to use `antlr4.generation.outputDir` to prevent the plugin from making a `.antlr` directory relative to my antlr files but changing it doesn't seem to work. I've restarted VSCode after updating the config and I'm still getting the `.antlr` directory.

For what it is worth I think creating a directory next to the source code isn't a great default either, but I'm happy to use the setting to move it. I just can't figure out how to get it working.

**Comment by mike-lischke** [comment]
The output dir is not for determining the location of the internal dir. It's common practice to have a local configuration dir (e.g. vscode creates `.vscode`) to store internal data. Nothing else is as straight forward and produces less problems than that. You could save in the temp folder of the system or the user's homedir, but all that requires extra mapping (to avoid using the same intermediate file names for grammars) and also destroys the locality between the grammar and the data that belongs to it (even if it is only internal). It's simple to ignre dot-folders e.g. in git (and you can even hide them in Linux + macOS).

**Comment by nik9000** [comment]
One of the things I really like about vscode is that it usually doesn't need extra git ignores. That just *feels* nicer even if it doesn't amount to much. I'll just create the gitignore.
