### ISSUE TITLE
Formatting comments adds empty lines in some situations

### ISSUE THREAD

**Issue by douira** [mike-lischke/vscode-antlr4#151]
Comments like the following are formatted to have an ever increasing number of empty lines:
```
//foo
//
```
Turns into:
```
//foo
//
//
```
With each formatting pass the number of empty `//` lines doubles. The same happens to block comments. This only happens if `reflowComments` is enabled.

**Comment by chris-miner** [comment]
Turns out that this only seems to happen if you have `reflowComments` set to true.
