### ISSUE TITLE
(Question) Can the extension generate tokens/tree based on some input language?

### ISSUE THREAD

**Issue by lispercat** [mike-lischke/vscode-antlr4#152]
In the way org.antlr.v4.gui.TestRig does it?
So that I could use the display the tree based on some input without having to use the TestRig or similar code?

**Comment by mike-lischke** [comment]
The extension can run and debug a parser/lexer with user supplied input. It optionally produces a text based tree and a graphical (interactive) tree. See also the [grammar debugging](https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/grammar-debugging.md) documentation.

**Comment by lispercat** [comment]
Great extension, thanks so much for your help!
