### ISSUE TITLE
highlighting & completion in a file described by a grammar

### ISSUE THREAD

**Issue by cgrandfield** [mike-lischke/vscode-antlr4#153]
I've found this extension useful. 

To confirm, it is entirely for the purpose of debugging grammar files and doesn't provide any assistance with debugging files written in such a grammar? Are the authors aware of any tools to give highlighting, completion to a file written in an antlr4 grammar?

I've found some discussion here : 

https://github.com/microsoft/language-server-protocol/issues/964
https://tomassetti.me/integrating-code-completion-in-visual-studio-code/

which suggest that it's possible to use antlr4 generated parsers to implement an LSP to provide highlighting, completion suggestions but there are not extensions at the moment which can do this just from the grammar.

**Comment by mike-lischke** [comment]
Tbh. I'm not sure what you mean by "...files written in such a grammar". Do you actually mean files generated from a grammar?

**Comment by cgrandfield** [comment]
they could be. Though I was thinking of handwritten files expected (but not guaranteed) to conform to the grammar

**Comment by mike-lischke** [comment]
Well, highlighting is specific to a file type. In my extension that's a grammar file (.g4 ending). An handwritten parser is something else and actually not even related to ANTL4 (for which this extension is made).

Debugging + code completion requires  the generated ATN, which you not have, if you didn't use ANTLR4. So its not usable as a general tool for a language server.

**Comment by cgrandfield** [comment]
i'm describing the scenario where you have a antlr .g4 grammar file that describes a grammar (let's say Mu) for .mu files. 

Your extension works very well to provide debugging + code completion in the antlr .g4 file 

I'm wondering what the path would be to get highlighting & completion in .mu type files using antlr4

**Comment by mike-lischke** [comment]
It's essentially as I already mentioned: for your .mu files you will need an own vscode extension, which provides the rules for syntax highlighting and implements a code completion provider. The latter may or may not use ANTLR4 for parsing.

However, that entire issue here is not related to the vscode-antlr4 extension. It's more of a general question how to provide language services for a specific file type.
