### ISSUE TITLE
Unable to fix error(8) grammar name and file name differ caused by filename casing on Windows

### ISSUE THREAD

**Issue by awschristou** [mike-lischke/vscode-antlr4#157]
I accidentally created my grammar file as a lowercase filename, and now I am unable to avoid the error(8) message. It seems like the extension has cached that errant pathname somehow.

Steps to reproduce:

(running on Windows)
- Install `mike-lischke.vscode-antlr4` extension in VS Code
- Open an empty folder in VS Code
- Set up workspace settings:
```json
{
    "antlr4.generation": {
        "mode": "external",
        "language": "CSharp",
        "listeners": false,
        "visitors": true
    }
}
```
- add file `foo.g4` with the following, and save the file
```
grammar Foo;
bar : BAR EOF;
BAR: 'bar';
```
- Outcomes:
  - I get a `FooLexer.cs` file generated (along with .interp and .tokens), but do not get a visitor generated
  - I get the following output in `ANTLR Exceptions`:
```
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true

error(8): foo.g4:1:8: grammar name Foo and file name foo.g4 differ
```

- I try renaming `foo.g4` to `xfoo.g4` and then back as `Foo.g4`
- I continue getting the same error and generated files.
- If I close and re-open VS Code, the behavior is the same
- If I uninstall the extension and re-install it, the behavior is the same

**Comment by mike-lischke** [comment]
Look in the `.antlr` subfolder in your vscode project folder, which contains all temporary/nternal files. You can simply remove it too and it will be recreated next time the grammar changes (or you open the project again).

**Comment by chris-miner** [comment]
I reproduced this problem.  My grammar name was `Rows` and it was in a file `Rows.g4`.  Then I changed the name of the grammar to lowercase `rows`.  This produced the error.  Then I changed the file name to 'rows.g4' and the error persisted.  I tracked down the issue to this bit of code in SourceContext.ts:
```
            const java = child_process.spawn("java", parameters, spawnOptions);
```
That's the code that calls something like:
```
java '-jar' '/usr/local/Cellar/antlr/4.9.3/antlr-4.9.3-complete.jar' '-message-format' 'antlr' '-o' '/Users/chris/Dev/antlr-examples/actions-js/grammars/.antlr' '-no-listener' '-no-visitor' '-Xexact-output-dir' '/Users/chris/Dev/antlr-examples/actions-js/grammars/Rows.g4'
```

Notice that the call to the antler tool still references the old file name `Rows.g4`.  At the command line you see the error:
```
chris@goldfish actions-js % java '-jar' '/usr/local/Cellar/antlr/4.9.3/antlr-4.9.3-complete.jar' '-message-format' 'antlr' '-o' '/Users/chris/Dev/antlr-examples/actions-js/grammars/.antlr' '-no-listener' '-no-visitor' '-Xexact-output-dir' '/Users/chris/Dev/antlr-examples/actions-js/grammars/Rows.g4'

error(8): Rows.g4:1:8: grammar name rows and file name Rows.g4 differ
chris@goldfish actions-js % 
```

If you change the name in that command from `Rows.g4` to `rows.g4` then you don't get the error:
```
chris@goldfish actions-js % java '-jar' '/usr/local/Cellar/antlr/4.9.3/antlr-4.9.3-complete.jar' '-message-format' 'antlr' '-o' '/Users/chris/Dev/antlr-examples/actions-js/grammars/.antlr' '-no-listener' '-no-visitor' '-Xexact-output-dir' '/Users/chris/Dev/antlr-examples/actions-js/grammars/rows.g4'

chris@goldfish actions-js % 
```
on my file system the file is lowercase `rows`.

**Comment by chris-miner** [comment]
A workaround for this was:
1. close the .g4 file after changing its name
2. reload the window (cmd-r) or Developer: Reload Window
3. re-open the file.

**Comment by mike-lischke** [comment]
This might actually be a problem of VS Code. I noticed on several occasions that VS Code still used the wrong casing and you had to close the file with the wrong name and open the correct one for VS Code to recognise the change. The extension uses the file name it gets from VS Code, so I'm unsure what to do here.

**Comment by tarilabs** [comment]
I had the same problem today and recognized per https://github.com/mike-lischke/vscode-antlr4/issues/157#issuecomment-1140255408 as the TAB had still the old name, I followed per https://github.com/mike-lischke/vscode-antlr4/issues/157#issuecomment-1095568461 workaround, when editor of .g4 was closed I erased the .antlr folder, reopened the .g4 file, space just to make it recognize changes, CTRL+S, solved.

🙏

**Comment by mike-lischke** [comment]
Looks like nothing can be done here from the extension side.
