### ISSUE TITLE
Add markdown syntax highlighting injection

### ISSUE THREAD

**Issue by hazer-hazer** [mike-lischke/vscode-antlr4#158]
I'm using "Markdown all in one" extension with `vscode-antlr4`, but anyway, when I write a codeblock in markdown neither `g4` or `antlr4` not working for syntax highlighting. It would be nice to highlight antlr4 code in markdown too.
I've tried to implement this in my fork with a simple injection.
https://github.com/hazer-hazer/vscode-antlr4

**Comment by mike-lischke** [comment]
Isn't that the wrong direction? You added markdown support in ANTLR4 files, but you want ANTLR4 highlighting support in markdown files actually. So you would have to inject ANTLR4 highlighting in the markdown definition, no?

**Comment by hazer-hazer** [comment]
@mike-lischke, I'm pretty sure I made ANTLR4 syntax injection to markdown. I've made some mistakes but fixed them, so now it works correctly and you can try it.

**Comment by hazer-hazer** [comment]
Also, this is just a feature I and maybe someone would like to have. So if you think that the package `vscode-antlr4` is a good place to include it, I'll make a pull request.

**Comment by mike-lischke** [comment]
The vscode-antlr4 extension does not trigger for markdown files. So, how can it inject itself into a markdown extensions? I have never done that kind of injection. However, if you can make it work then open a PR and I learn from your code :-)

**Comment by hazer-hazer** [comment]
@mike-lischke, #159 PR is here
