### ISSUE TITLE
Files generated in `.antlr` directory

### ISSUE THREAD

**Issue by BurtHarris** [mike-lischke/vscode-antlr4#16]
I haven't looked closely at **vscode-antlr4**, but I *am* using it.   *Thanks Mike.*

I noticed generated files getting added to a `.antlr` directory under where my `.g4` files are located.   I'm guessing this came from **vscode-antlr4**, right?

I'm not saying that is a bug, in fact I was thinking about doing something similar in **antlr4ts-cli**, though I considered putting it in a temp directory outside the source tree.   Is there some reason you chose to put it into the source directory?   Any related thoughts?

I'm also interested in the ".interp" file format generated in this directory.   Can you point me at anything about this format?

**Comment by mike-lischke** [comment]
Right, the extension uses local `.antlr` folders. Of course it would be possible to use the temp folder, but then you have to take care to avoid naming collisions. It's definitely more tricky to makes this properly working than just using a local folder. Locality is much higher when you put generated data close to the grammars etc. Are the `.antlr` folders a problem for you?

The interpreter data is something I introduced. Nothing complicated, just an export of the ATN, rule names, mode names, channels, etc. Terence added my patch for generating this data to ANTLR 4.7.1 recently, so this data should be available now by default. I'm right now in the process to use that to create interpreters in TS and have debugging support for ANTLR4 grammars in vscode. There's a reader for that (plain text) data in ANTLR4 and I also [added one in the TS target](https://github.com/mike-lischke/antlr4-graps/blob/master/src/InterpreterDataReader.ts).

**Comment by BurtHarris** [comment]
Thanks Mike, no problem a line in .gitignore can't fix.  

I'll have a look at the .interp file generation, It may be educational.

**Comment by Mi-La** [comment]
Hi Mike,
Would it be possible to add some configuration for location where the ".anltr" folder is created? Unfortunately for me it's at least uncomfortable to have the folder silently generated somewhere in my source tree.
Thanks

**Comment by mike-lischke** [comment]
@Mi-La when you have a solution for that I'm all ears. Create a pull request with changes required to manage a configurable internal folder, separated by each possible grammar location.

**Comment by Mi-La** [comment]
@mike-lischke :-). I'm afraid that we will have to wait until it will bother me much more or until it will bother somebody else who has more time to play with it. Right now I just wanted to "vote" for improvement.
