### ISSUE TITLE
VSCode ANTLR Extension Not Activating

### ISSUE THREAD

**Issue by mwhitfo** [mike-lischke/vscode-antlr4#167]
Hi, 

Installed the extension, and nothing was being autogenerated. Upon looking into the issue a bit further, it seems that the extension doesn't want to activate? I re-installed VSCode as I thought maybe it was an issue with the IDE, but I tried a couple other extensions out and they are working fine. There doesn't seem to be much that I could find online about this issue, so I'm curious to hear your thoughts and if this problem has been encountered before.

Enclosed are two screenshots. At first when I install the extension, it gives me a Runtime Status of "No status available", and then once I open up a .g4 file, it attempts to activate the extension and then I get "Not yet activated" as the Runtime Status

![ANTLR_First_Status](https://user-images.githubusercontent.com/60940198/162246984-332a463c-39bf-4580-8e6a-b5f90e4f2406.PNG)

![ANTLR_Second_Status](https://user-images.githubusercontent.com/60940198/162246983-508c96ee-22ba-46bb-9016-ea6fb1421dfd.PNG)

**Comment by mike-lischke** [comment]
That's pretty unusual. Can you check the OUTPUT tab for any error message. See if there's anything that hints at a reason why the extension doesn't activate. Do you have Java installed? That's needed for ANTLR4, but I believe the extension should still activate.

**Comment by mwhitfo** [comment]
Here's a copy of the error message in the OUTPUT tab:
![ANTLR_Extension_Error_Output](https://user-images.githubusercontent.com/60940198/162286645-55e8034f-4dfb-465e-a5df-00e6c45f3705.PNG)

And this is the Java version I have installed:
![Java_Version](https://user-images.githubusercontent.com/60940198/162286747-e8121464-446a-4fb7-b271-61430f93f827.PNG)

One thing to add that is strange is that other people in my organization have seemed to install the extension and use it on this exact repo with no issue

**Comment by mike-lischke** [comment]
The error indicates that something with a stored interpreter data file is wrong. Try removing the `.antlr` folder (it will automatically be regenerated) and see if that helps.

**Comment by mwhitfo** [comment]
So removing the .antlr folder seems to get the extension to activate; however, the autogeneration still does not work completely correctly. The original repo I cloned generated files in Typescript, but I would like the files to be generated in C#. After updating the JSON file that defines "antlr4.generation" to have the language be C#, it **still autogenerates in Typescript**. Thoughts? 

This picture is the original way it was defined:
![OriginalSettings](https://user-images.githubusercontent.com/60940198/162483997-5bf7379f-aeb0-4cc5-b7b7-77a2da5be715.PNG)

This is how I updated the file:
![UpdatedSettings](https://user-images.githubusercontent.com/60940198/162484030-6abd4211-dec1-4d46-8a9f-c7067b591e63.PNG)

**Comment by mike-lischke** [comment]
In external mode the output should be for the target language specified in the settings. Try varying the language string (e.g. use "csharp" instead). This is directly passed on to the the ANTLR4 jar when generating.

**Comment by mwhitfo** [comment]
No luck with that unfortunately, tried with "Java" and "java" as the target languages as well, and still seems to be generating in Typescript

**Comment by mike-lischke** [comment]
I just released version 2.2.5 and tested code generation right before that. Everything seems to be working fine. Can you give it a try and see if that solves your problem?

**Comment by mwhitfo** [comment]
Looks like it's now working with the update! Thanks!

**Comment by mike-lischke** [comment]
Excellent. Thanks for the report.
