### ISSUE TITLE
Parse Tree view doesn't update parse/lex rule names when they change

### ISSUE THREAD

**Issue by chris-miner** [mike-lischke/vscode-antlr4#168]
I did the following:
1. created a simple grammar with one parse rule, and one lexer rule
2. created a sample data file
3. launched the "Debug ANTLR4 grammar" item referencing the grammar and data file
4. the system produced a lovely parse tree complete with labels for the rules represented
5. changed a name of a rule
6. repeated step 3

Found:
The lovely parse tree labels are not updated to reflect the new rule names

Workaround:
If you collapse the part of the tree with the as yet not updated label, and then re-expand it, the labels update.

**Comment by TheBoz** [comment]
This issue still exists today in the latest version, but now it requires opening and re-starting VSCode to get the labels to update. 
Is there any insight into why this is happening and when/f it will be fixed?

**Comment by mike-lischke** [comment]
Fixed in release 2.4.0
