### ISSUE TITLE
'Go to Definition' not working

### ISSUE THREAD

**Issue by EternalPhane** [mike-lischke/vscode-antlr4#17]
happens after commit https://github.com/mike-lischke/vscode-antlr4/commit/c185175c958552d70d22b6d924a6bb81757c785c#diff-9e104f81fe91f5fa268b1d7193109c23

![screenshot](https://user-images.githubusercontent.com/11267872/34714410-58344a40-f564-11e7-8c7d-cc4710df2a78.gif)

**Comment by ydogus** [comment]
Same here. It says:

> Unable to open 'XYZParser': File not found (file:///XYZParser).
