### ISSUE TITLE
Predicate and action transitions should be marked

### ISSUE THREAD

**Issue by KvanTTT** [mike-lischke/vscode-antlr4#170]
### Grammar

```g4
lexer grammar Test;
TOKEN_WITH_ACTION: {predicate()}? 'x' {action()};
```

### ATN

![image](https://user-images.githubusercontent.com/1150330/166311195-ea01d68e-8f1a-49c9-89cf-1042ad5765f0.png)

### Expected ATN

Transitions `7->8`, `9->10` should be marked as sempred and action. Currently they are misleading.

**Comment by mike-lischke** [comment]
Yes, that's planned. I already added transition descriptions:

![enhanced-atn-graph](https://user-images.githubusercontent.com/2398704/166315302-82b6f5e9-7650-4c62-953e-63111e8cfa59.png)

**Comment by mike-lischke** [comment]
Added in release 2.2.5.
