### ISSUE TITLE
Syntax security check

### ISSUE THREAD

**Issue by Bestduan** [mike-lischke/vscode-antlr4#171]
This is a very good extension, greatly improve the efficiency of my development, thank you for your pay. 
But I found that after the actual generated js code in js operation will cause an infinite loop, but in the use of this extension does not appear the same problem when I debug. 
`jar :  antlr-4.7.2-complete.jar`
`antlr4js :  "antlr4": "^4.8.0"`
`command : java -jar /opt/antlr4/antlr-4.7.2-complete.jar -Dlanguage=JavaScript test.g4`
So is there a safety check of the infinite loop program happen, or how to avoid such a question.
Looking forward to your reply.

**Comment by mike-lischke** [comment]
You wonder why you don't see an infinite loop when debugging a grammar in the extension? The extension does not use a real parser, but instead runs an interpreter step-wise. This way it can handle break points.

The reason why that endless loop happen is however out of scope of this extension. You probably should first upgrade to the latest ANTLR4 tool and the JS runtime and if you still see the problem, file a bug report in the ANTLR4 repository.

**Comment by Bestduan** [comment]
So do you think this might be due to the lower version of ANTLR4? 
In addition, does this extension debug g4 files by generating ts files and then running them?

**Comment by mike-lischke** [comment]
> So do you think this might be due to the lower version of ANTLR4? 

Could be, but I don't know the JS target. This extension is about working with grammar files, not with the individual targets.

> In addition, does this extension debug g4 files by generating ts files and then running them?

No. The extension uses the interpreter class to manually walk over the ATN to run the parsing process.
