### ISSUE TITLE
Cannot save railroad diagrams

### ISSUE THREAD

**Issue by startibartfast** [mike-lischke/vscode-antlr4#179]
When I click the 'Save to PNG' button, for single rule, or 'Save to HTML' button for all rules diagram, nothing happens.

**Comment by bertrandm** [comment]
Experiencing the self-same issue. Want to use this feature to document system, but cannot. Would appreciate any workaround if possible.

**Comment by classicwuhao** [comment]
The same problem here, any advice? I also want to document grammar for our project.

**Comment by Orgl9l** [comment]
@classicwuhao I found an alternative for creating railroad diagrams, downside is that you have to make them by hand, depending upon complexity of your grammar this may or may not work for you. After a while I got good at it, and I was able to cut and paste the SVG into my documents, and it works wonderfully, also could style it with css.
[Railroad Diagram Generator](https://tabatkins.github.io/railroad-diagrams/generator.html#Diagram(%0ANonTerminal('rule')%2C%0ATerminal('rule_name')%2C%0ATerminal('event_type')%2C%0ANonTerminal('%7B')%2C%0ATerminal('rule_body')%2C%0ANonTerminal('%7D')%20)%0A)

**Comment by classicwuhao** [comment]
@Orgl9l Thanks, I will try, I have 500+ lines of grammar... GG.

**Comment by toongeorges** [comment]
Here is a work around (probably not the best one, but it does the job):

First locate where the VSCode is installed, typically under something like `${USER_HOME}/.vscode/extensions/mike-lischke.vscode-antlr4-2.3.0`.  Let the value of `${ROOT}` be this directory.

The files you want to change are under the directory `${ROOT}/out/src/frontend/webviews/`.  To get the railroad diagram for a single rule, you can change the file `${ROOT}/out/src/frontend/webviews/RailroadDiagramProvider.d.ts` as follows:

Change

            diagram += `
                <div class="header">
                    <span class="rrd-color">
                        <span class="graph-initial">Ⓡ</span>ule&nbsp;&nbsp;
                    </span>
                        &nbsp;&nbsp;${this.currentRule} <span class="rule-index">(rule index: ${this.currentRuleIndex})
                    </span>
                    <span class="action-box">
                        Save to SVG
                        <a onClick="exportToSVG('rrd', '${this.currentRule}');">
                            <span class="rrd-save-image" />
                        </a>
                    </span>
                </div>
                <div id="container">
                    <script>${this.backend.getRRDScript(fileName, this.currentRule)}</script>
                </div>
            `;

to

            diagram += `
                <div class="header">
                    <span class="rrd-color">
                        <span class="graph-initial">Ⓡ</span>ule&nbsp;&nbsp;
                    </span>
                        &nbsp;&nbsp;${this.currentRule} <span class="rule-index">(rule index: ${this.currentRuleIndex})
                    </span>
                    <span class="action-box">
                        Save to SVG
                        <a onClick="exportToSVG('rrd', '${this.currentRule}');">
                            <span class="rrd-save-image" />
                        </a>
                    </span>
                </div>
                <div>
                  <button onclick="readSVG()">read SVG</button>
                </div>
                <div>
                  <pre id="content">
                  </pre>
                </div>
                <script>
                  function readSVG() {
                    const source = document.getElementById('container').getElementsByTagName('svg')[0];
                    const destination = document.getElementById('content');
                    destination.innerHTML = source.outerHTML
                                                  .replaceAll('&', '&amp;')
                                                  .replaceAll('<', '&lt;')
                                                  .replaceAll('>', '&gt;')
                                                  .replaceAll('"', '&quot;')
                                                  .replaceAll("'", '&#039;');
                  }
                </script>
                <div id="container">
                    <script>${this.backend.getRRDScript(fileName, this.currentRule)}</script>
                </div>
            `;

You will now have a button in the user interface that you can click to print the SVG as text in the window.  You can copy this text to a new SVG file.

**Comment by mike-lischke** [comment]
A new release (2.4.0) was just published, with a much improved RRD handling.
