### ISSUE TITLE
How to pass multi CLI arguments to antlr?

### ISSUE THREAD

**Issue by ArcticLampyrid** [mike-lischke/vscode-antlr4#180]
Like #69
`options.additionalParameters` only supports to pass a single argument currently.

----
A detailed example:
```
{
    "antlr4.generation": {
        "additionalParameters": "-encoding UTF8"
    }
}
```
will pass `"-encoding UTF8"` instead of `"-encoding" "UTF8"`

**Comment by JohnLouderback** [comment]
I'm experiencing the same issue. The encoding is being interpreted incorrectly, but I don't seem to have any way to pass it in.

**Comment by ArcticLampyrid** [comment]
For encoding problems, since VSCode did't yet provide encoding-related APIs (microsoft/vscode#156039), it's impossible to handle it perfectly.
But I recommend to use `UTF-8` by default in CLI arguments, as many parts of this extension have assumed that the encoding is `UTF-8` when analyzing the grammar files.
