### ISSUE TITLE
Can't make visualization work (railroad diagram and Antlr view)

### ISSUE THREAD

**Issue by hl037** [mike-lischke/vscode-antlr4#181]
Hi,
I installed the extension yesterday, but I can't make it work...

Here what I get :

![image](https://user-images.githubusercontent.com/2771764/183281193-fc9c31ab-7a8e-4c4d-be99-49fd2d2154f4.png)

There is some indicator in the antlr view that my tell some work is done in the background, but after 10 minutes, nothing new. (and this grammar really not that long...

The call graph seems to work though.

Any tip ?

**Comment by mike-lischke** [comment]
Try setting the caret into a rule text. Does this show the RRD for this rule?

**Comment by hl037** [comment]
Actually, it was on the body rule (but the screenshot does not show it because of the blinking)

**Comment by DeLuxe-1337** [comment]
I also have this issue.

**Comment by izmalk** [comment]
Same problem. Any news?

**Comment by mike-lischke** [comment]
A new release (2.4.0) was just published, which now works with the latest ANTLR4 version.
