### ISSUE TITLE
Setting no generation language should not automatically apply Java as default

### ISSUE THREAD

**Issue by ralfhandl** [mike-lischke/vscode-antlr4#182]
I have a monorepo with two sub-projects using ANTLR4, one generating a JavaScript parser from grammar `foo.g4`, the other generating a TypeScript parser from grammar `bar.g4`.

According to [Extension Settings/Parser Generation](https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/extension-settings.md#parser-generation)

> - **language**, string (default: "Java"), specifies the target language for the generated code, overriding what is specified in the grammar (used only in external mode)

Specifying the target language in the grammar, for example
~~~antlr
grammar foo;

options { language=JavaScript; }
~~~

does not result in a JavaScript parser, instead a Java parser is generated.

How can I get this working?

**Comment by mike-lischke** [comment]
IIRC the language name must be all lower case.

**Comment by ralfhandl** [comment]
@mike-lischke I tried with all-lower case, here `options { language=javascript; }`, and still only get Java code generated.

The phrase 

> overriding what is specified in the grammar (used only in external mode)

in the extension documentation led me to believe that this extension would take into account what is specified in the grammar:
is that the intention?

**Comment by ralfhandl** [comment]
Ok, found it: setting the language to `null` suppresses the `-Dlanguage=xxx` option and lets Antlr take the grammar-specified language:

~~~json
  "antlr4.generation": {
    "mode": "external",
    "language": null,
    "outputDir": "parser"
  },
~~~

Is this an official feature worth mentioning in the extension documentation?

**Comment by mike-lischke** [comment]
Ah yes, I forgot that command line language overrides the grammar language. You can just entirely remove the language setting from the options.

**Comment by ralfhandl** [comment]
> You can just entirely remove the language setting from the options.

Unfortunately not: in this case the extension seems to pass `-Dlanguage=Java` to Antlr.

Only explicitly setting `"language": null` does the trick.

**Comment by ralfhandl** [comment]
Which is kind of redundant because Antlr silently falls back to Java if neither the command line nor the grammar specifies a target language.

It would be better if the extension would not to pass a `-Dlanguage=...` option if no language is set in the VS Code settings.

**Comment by mike-lischke** [comment]
Good point. Let's make this a bug report.
