### ISSUE TITLE
VSCodium

### ISSUE THREAD

**Issue by siliconvoodoo** [mike-lischke/vscode-antlr4#184]
Would be nice to have codium support. Idk if it's just a question of publication.

**Comment by mike-lischke** [comment]
I have to check out first what's required, but I assume I have at least to register me somewhere. Anyone knows the details? The page https://vscodium.com/ doesn't mention anything related to extensions.

**Comment by mariolpantunes** [comment]
The information is [here](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace).
The important part is that VSCodium uses [Open VSX Registry](https://open-vsx.org/) by default.
I assume that registering the extension there should be enough.

**Comment by mike-lischke** [comment]
It's now available there: https://open-vsx.org/extension/mike-lischke/vscode-antlr4
