### ISSUE TITLE
Using +? crashes the extension

### ISSUE THREAD

**Issue by K1T3K1** [mike-lischke/vscode-antlr4#186]
I'm new to antlr so I may be just stupid, but here's the thing.
Writing something like this `` ( TOKEN1 | TOKEN2 | TOKEN3 )+? `` crashes the extension, but ``( TOKEN1 | TOKEN2 | TOKEN3 )+`` or ``( TOKEN1 | TOKEN2 | TOKEN3 )?`` works like a charm. It shows such an error:
![image](https://user-images.githubusercontent.com/89193001/191478911-fd1e7302-82e8-4022-ae55-f732f2e4de89.png)
Is it something wrong with the +? syntax? Antlr documentation shows it is allowed.

**Comment by mike-lischke** [comment]
That looks very much like a bug (unhandled condition somewhere).

**Comment by mike-lischke** [comment]
@K1T3K1 I cannot reproduce this problem. Can you attach a grammar here which shows this problem?
