### ISSUE TITLE
Feature: Generate interpreter data at launch if it doesn't exist.

### ISSUE THREAD

**Issue by eseglem** [mike-lischke/vscode-antlr4#189]
It had been a while since I had used this extension and was starting from a clean git repo without the generated `.antlr/` directory in it. I could not for the life of me get debugging to launch. I just wanted to trace through an input on an existing grammar. It wasn't until I accidentally triggered a save on the `.g4` file and it generated files that I understood what was happening. 

I know debug probably doesn't get launched much without changing the files, but it would be very nice to add that a check in there.

**Comment by mike-lischke** [comment]
Creating the target files upfront, while starting up, could delay the extension launch, leading so to warnings from VS Code. Probably not a good idea.

**Comment by mike-lischke** [comment]
Right, it would be helpful if the debugger files were generated, if they don't exist yet. I modelled the behavior after what's done with other generated files (e.g. typescript). You cannot debug them without an intermediate build step that transpiles them.

However, once this is set up, the transpilation happens always, even for new TS files. So this could be the next step for the ANTLR4 extension (just without a separate setup step).

**Comment by mike-lischke** [comment]
Implemented as part of commit #195.
