### ISSUE TITLE
Unable to fix error(8) "grammar name and file name differ", caused by filename casing on Windows

### ISSUE THREAD

**Issue by jeancallisti** [mike-lischke/vscode-antlr4#191]
Hello,

First of all, thanks a lot for this amazing extension.

This issue is a duplicate of https://giters.com/mike-lischke/vscode-antlr4/issues/157 (it's not possible to post updates on Giter)

I have some updates regarding this : 
**1) The workarounds don't work** (deleting .antlr and all other generated files entirely, and restarting VSCode (with or without the "restart window" command) doesn't help -- the error comes back the second I Ctrl+S the g4 file again)
**2) I think this is definitely a VSCode issue** : It caches the files names somehwere. I see many other unrelated extensions that have the same issue (jsx, etc.)
 3) The issue might be more present for people who have **WSL** installed, somehow. I've seen clues to that here and there. EDIT: I've run the Windows command to check the case sensitivity setting of the folder that contains my g4 file; it says the attribute is **disabled.**

As explained in the Giter issue, the problem appears only when the file is created with the wrong casing first and later changed.

**Comment by jeancallisti** [comment]
I've tried deleting 
C:\Users\USER\AppData\Roaming\Code\CachedData
C:\Users\USER\AppData\Roaming\Code\Cache

Still not helping.

**Comment by jeancallisti** [comment]
WORKAROUND: 

- Close VSCode
- Delete all generated files (**.antlr** folder and files like **XXXLexer.cs**, **XXXVisitor.cs**, etc.)
- Delete your "bad" g4 file (create a backup first, obviously!)
- Open Windows command prompt
- Go to your grammar folder : `cd C:\xxx\`
- **Turn on folder's case-sensitivity :** `fsutil.exe file setCaseSensitiveInfo . enable`
- Open VSCode.
- Recreate g4 file with correct casing. If VSCode complains that it can't, reload the window again (Ctrl+shit+P--> Reload window).
- Check that the first line ( `grammar MyGrammar;` ) has the same casing.
- Save the g4 file. It now recreates all the generated files with the correct casing!
- Close VSCode
- **Turn the case-sensitivity of the folder back off:** `fsutil.exe file setCaseSensitiveInfo . disable`
- Re-open VSCode and work normally!

**Comment by jeancallisti** [comment]
I've tried that too, I don't think it works (I didn't pay a lot of attention, but I did try). It's really the file's name that remains somewhere, regardless of the grammar or anything else.

**Comment by chris-miner** [comment]
I had this same problem on macOS.  So, it isn't just a Windows thing.  This is on my (mental) list of things to debug.

**Comment by mike-lischke** [comment]
Might also be a VS Code problem. I have just seen a similar problem with a readme file, which I renamed (and had it open in a tab). Even after restart VS Code would come up with the old file name.

**Comment by mike-lischke** [comment]
Looks like there's no more to do here.
