### ISSUE TITLE
Broken Parse Tree Window on VSCode v1.73

### ISSUE THREAD

**Issue by c4lcifer** [mike-lischke/vscode-antlr4#192]
i recently updated VScode from 1.67.2 to latest 1.73 on Ubuntu 22.04

After this upgrade the graphs were no longer drawn. It would still open the parse tree window, but it would stay blank.
I am using antlr4-python-runtime 4.9.3 and vscode-antlr4 2.3.0

Only a reinstall of vscode 1.67.2 fixed the issue for me. I did not test any other VSCode versions

**Comment by mike-lischke** [comment]
This is the result of an ever ongoing battle for browser security:

> index.html?id=e9cf786f-f809-419b-a31d-a992fcabf91c&origin=f0aaeb52-265d-411a-bb60-1811d7564ae5&swVersion=4&extensionId=mike-lischke.vscode-antlr4&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:969 Refused to load the script 'vscode-resource:/Users/mike/.vscode/extensions/mike-lischke.vscode-antlr4-2.3.0/node_modules/d3/dist/d3.js' because it violates the following Content Security Policy directive: "script-src 'self' https://*.vscode-cdn.net 'self' 'unsafe-inline' 'unsafe-eval' https:". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
