### ISSUE TITLE
Question: Antlr4.Runtime.Standard compatibility

### ISSUE THREAD

**Issue by swidz** [mike-lischke/vscode-antlr4#193]
What is the current version compatibility with Antlr4.Runtime.Standard package
Current version of Antlr4.Runtime.Standard is 4.11.1
Current VSCode extension is 2.3.1 which I guess uses ANTLR 4.9.2

Does it mean that the version of Antlr4.Runtime.Standard package referenced in C# project should also be 4.9.2 ?

**Comment by mike-lischke** [comment]
Right, currently only 4.9 is supported, as I have no typescript runtime for 4.11.

**Comment by swidz** [comment]
There was also version 4.9.3 released 
Perhaps it would be compatible with vscode-antlr4?
On the other hand it did not bring much to C# parser generation.
Not sure about changes introduced in Antlr4.Runtime.Standard 4.9.3 package though

**Comment by mike-lischke** [comment]
It's certainly compatible (just a build version change), but that would probably not change the C# parser generation. I'm working on a 4.11 runtime currently, so at some point the extension will likely support that version too.

**Comment by swidz** [comment]
Thanks for clearing that up.
