### ISSUE TITLE
Extension breaks if filename ends with Parser

### ISSUE THREAD

**Issue by Vince7778** [mike-lischke/vscode-antlr4#195]
If the grammar name ends with "Parser", such as in my case a file named "APPParser.g4", the extension behaves improperly. 4 of the 5 panels in the ANTLR view don't load, and the debugger gives an error "TypeError: Cannot set property 'inputStream' of undefined". Changing the file name to anything else fixes the issue.

Screenshot:
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/32619800/210191148-d60584c7-7c36-4d93-9bd4-8185fcb6d6f3.png">

(This was a hell of a bug to figure out...)

**Comment by mike-lischke** [comment]
I'm sorry for the trouble, but actual file cannot be the culprit. In my test environment are are many grammars, all ending with "Parser.g4", so if that were a problem, it would have shown up already a long time ago. Maybe there's a conflict with cached data? See if removing the `.antlr` folder (where your grammar is) changes things somehow...

**Comment by Vince7778** [comment]
Removing the `.antlr` folder didn't change anything, unfortunately. Even in a completely new project, it still breaks if the filename ends with "Parser.g4". 

Here's a copy of a test project that's broken for me:
[test-antlr4.zip](https://github.com/mike-lischke/vscode-antlr4/files/10333668/test-antlr4.zip)

**Comment by mike-lischke** [comment]
Fixed, thanks for the report.
