### ISSUE TITLE
Use lexer token labels when generating tokens in debug console

### ISSUE THREAD

**Issue by tobiade** [mike-lischke/vscode-antlr4#197]
Hello!
I was wondering if it's possible to get the following token output in the Debug Console when generating the parse tree for a sample input. For example, given the following input: `make x = 4`, this is the output I get when I run `grun` with the `-tokens` flag set:
```
[@0,0:3='make',<'make'>,1:0]
[@1,5:5='x',<IDENTIFIER>,1:5]
[@2,7:7='=',<'='>,1:7]
[@3,9:9='4',<INT>,1:9]
[@4,10:10='\n',<EOS>,1:10]
[@5,11:10='<EOF>',<EOF>,2:0]
```

However, when I user the antlr4 VSCode extension, I get the following:
```
[@0,0:3='make',<10>,1:0]
[@1,5:5='x',<23>,1:5]
[@2,7:7='=',<21>,1:7]
[@3,9:9='4',<22>,1:9]
[@4,10:10='\n',<25>,1:10]
[@5,11:10='<EOF>',<-1>,2:0]
```

In the latter case, the token labels e.g `IDENTIFIER` seem to be replaced by their IDs (`23`). 

Is it possible to show the lexer token labels instead (like the former case)?

If this needs an enhancement,  I'm happy to pick it up if you can point me where to go.

ANTLR version is `4.11.1`

**Comment by mike-lischke** [comment]
Have you checked the [debugger documentation](https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/grammar-debugging.md)? It describes how to enable text output when debugging a grammar, including the token list you mentioned.

**Comment by tobiade** [comment]
Sweet, thank you.
