### ISSUE TITLE
Could not prepare debug session

### ISSUE THREAD

**Issue by Dot-H** [mike-lischke/vscode-antlr4#198]
Hi,

I have trouble making the extension work. I am trying to visualise the generated AST for a specific input but I always get the error: `Error: Debugger creation failed. You are either trying to debug an unsupported file type or no interpreter data has been generated yet for the given grammar.`.

Sorry I cannot give you more insight but I couldn't find any log in vscode, nothing is printed in neither the output nor the debug console 😕 

Here is my launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug ANTLR4 grammar (preview)",
            "type": "antlr-debug",
            "request": "launch",
            "input": "sample.formula",
            "grammar": "Parser.g4",
            "startRule": "previewUnit",
            "printParseTree": true,
            "visualParseTree": true
        },
    ]
}
```

**Comment by mike-lischke** [comment]
This might have to do with issue #195 which I just fixed.

**Comment by Dot-H** [comment]
That was it, it works if I rename it thanks 👌
