### ISSUE TITLE
Correct errors in an Antlr .g4 files does not remove messages from the OUTPUT window.

### ISSUE THREAD

**Issue by Korporal** [mike-lischke/vscode-antlr4#199]
If I edit a .g4 file and introduce an error, then save that file, an error/warning appears in the OUTPUT window pane. If I then correct the error and save the file, the error/warning remains.

**Comment by mike-lischke** [comment]
It's like that by intention. The output is like a terminal, where you also can still see past errors when you fix them. The current list of errors is in the `PROBLEMS` plane.
