### ISSUE TITLE
Unnecessary `Duplicate symbol` error when two different grammars are in the same directory

### ISSUE THREAD

**Issue by millergarym** [mike-lischke/vscode-antlr4#2]
When there are two unrelated grammars in the same directory the same rules name in both files causes a Duplicate symbol error. Both grammars are totally valid and the Antlr tools is fine with them.

It would be nice in the plugin didn't complain.

**Comment by mike-lischke** [comment]
I just tried to reproduce this issue, but can't. What exactly are you doing to get the wrong duplicate symbol error? Is that problem limited to specific type of grammar (e.g. combined vs separate grammars)?

**Comment by mike-lischke** [comment]
Can you try the latest release? Does this issue still show up for you?
