### ISSUE TITLE
parse tree

### ISSUE THREAD

**Issue by fheidrich** [mike-lischke/vscode-antlr4#20]
I really liked this plugin but I really miss the parseTree view I had back in IntelliJ and Eclipse.
Basically given a grammar and example source input it display the AST graphically.
ideally, the example source input could be a file or a text area + with live update over the AST graph view.

If this feature is already in please let me know who to fire it up.

Many Thanks
Felipe

**Comment by mike-lischke** [comment]
The debugger is under work currently. Here's a sshot of the current build:

![debugger](https://user-images.githubusercontent.com/2398704/35285920-d534ccea-005e-11e8-8c6e-3aec235fd843.png)

However, it will take a bit time yet to complete that work. What works already is setting up a launch config for debugging where you specify an input file, the start rule and optionally a grammar file (or the current editor is used if that's a grammar, if not given). A token list is produced from the input and that parse tree. No breakpoints yet, or step through.

**Comment by fheidrich** [comment]
That is really cool ! I tried to create a launch configuration but could not figure out how to specify the start rule (nor the grammar file), and it won't work when I ran it (whatever launch exception).
Would you mind sharing a launch configuration example ? Thanks

**Comment by mike-lischke** [comment]
You checked out the debugger branch? This functionality is not available in master yet! When you have to correct sources vscode should provide with a default launch configuration, including help about what each field means.

**Comment by fheidrich** [comment]
Hi, checked out the branch and tried to build it using 'npm install', and ' npm run compile' 
I hoped that would do the trick, but it seems something is off with tsc compiler (doesn't like some of the flags in there (allowSyntheticDefaultImports/strictNullChecks/allowJs)
I tried installing typescript globally but it didn't help me.

is there any building instructions ? Thanks
(sorry, i've never done typescript nor vscode plugin development)

**Comment by mike-lischke** [comment]
Unfortunately, there's even more to this. You also need the latest [antlr4-graps](https://github.com/mike-lischke/antlr4-graps) node module code. First do an `npm install` in antlr4-vscode to get all node modules. Then remove the antlr4-graps folder in it's node_modules folder and link the repo to it instead (see `npm link`). Finally open vscode and open the antlr4-vscode folder in it. Then launch that. The TS transpiler in vscode should do the transpilation job automatically. When the debugging session launches you can open a new workspace or folder (that with your grammar(s)). It will be stored and reopened every time when you start that extension debugging (unless you open it regularly). And in this workspace you can then set up grammar debugging.

A bit convoluted and you should expect problems, since this is WIP.

**Comment by fheidrich** [comment]
Sorry for the delay, I had a few days off. Anyway, I tried and failed

git clone https://github.com/mike-lischke/antlr4-graps.git
cd antlr4-graps/
git checkout debugger
npm install
npm link
cd ..
git clone https://github.com/mike-lischke/vscode-antlr4.git
cd vscode-antlr4/
git checkout debugger
npm install (for an error at postscript)
rm -rf node_modules/antlr4-graps
npm link  antlr4-graps

launch code point to vscode-antlr4 and run the extensionHost (named "Extension starten").
Extension fails to load, in the log

../antlr4-graps/src/GrapsDebugger.ts(59,13): error TS7027: Unreachable code detected.
src/ATNGraphProvider.ts(15,50): error TS2307: Cannot find module 'vscode'.
src/ATNGraphProvider.ts(29,50): error TS2304: Cannot find name 'Thenable'.
src/ATNGraphProvider.ts(33,59): error TS7006: Parameter 'document' implicitly has an 'any' type.
src/ATNGraphProvider.ts(133,25): error TS7006: Parameter 'value' implicitly has an 'any' type.
src/AntlrDebugger.ts(16,67): error TS2307: Cannot find module 'vscode'.
src/AntlrDebugger.ts(134,25): error TS7006: Parameter 'reason' implicitly has an 'any' type.
...

Easy to fix or maybe just wait till you are done ?
Thanks!

**Comment by mike-lischke** [comment]
Well, better you wait for this feature to be available. Shouldn't take that long anymore.
