### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hyx-hyx** [mike-lischke/vscode-antlr4#201]
- Issue Type: `Performance`
- Extension Name: `vscode-antlr4`
- Extension Version: `2.3.1`
- OS Version: `Windows_NT x64 10.0.22623`
- VS Code version: `1.75.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Lenovo/AppData/Local/Temp/mike-lischke.vscode-antlr4-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mike-lischke** [comment]
You neither described what you did when this event occurred nor have you attached the cpu profile file. What do you expect I can do with this report?
