### ISSUE TITLE
project not configured to run in development environment "out of the box"

### ISSUE THREAD

**Issue by chris-miner** [mike-lischke/vscode-antlr4#204]
I did the following:
1. forked the vscode-antlr4 project
2. cloned the fork
3. cd into the project directory
4. executed npm install
5. opened the project in vs code
6. clicked on launch extension

found:
error output in terminal
> *  Executing task: tsc -b -w 
> 
> *  The terminal process failed to launch: Path to shell executable "tsc" does not exist.

expected:
I thought the project would pop up in a new Extension Development Host window

Extra info:
This is related to #166

**Comment by chris-miner** [comment]
Had to find my old issue to figure out again how to resolve this one, which is basically the same.  One could say the problem comes about because I don't have typescript installed and therefore no tsc.  The tsc command is basically run directly in the shell and uses whatever version of tsc you happen to  have lying around.  In the case of #166 this meant that I got a bunch of weird errors that nobody with the correct version would see.

The solution, in my opinion, is to run tsc from npm.  This way you use the version of typescript configured in the project (4.9.5) in this case.  Running tsc from npm has the added benefit that the project works "out of the box".

My remedy was to:
1. add a script to the package.json file ("tsc": "tsc -b -w")
2. replace the tsc task with a version that uses npm to run the tsc script
3. change the debug launch configuration to use this as the pre-launch task

**Comment by mike-lischke** [comment]
I never investigated which tsc binary is run in the different situations (in a standalone terminal, in a vscode terminal, as part of launch task). What gets precedence if you have both, a global installation and a local one of typescript?

From a resource standpoint it makes probably sense to use a global installation and do not add a dev dep to your typescript projects. On the other hand that might produce problems if your globally installed version does not match a required version. You could upgrade, but that might break other projects. Tricky problem...

**Comment by chris-miner** [comment]
> What gets precedence if you have both, a global installation and a local one of typescript?

I don't think there is a precedence wrt the tsc used.  If you run tsc on the command line you get whatever is in your path.  This is why launching the freshly cloned project did not work for me this time (no tsc on my path) or last time (wrong version of tsc on my path and the project version was not used).  If you run via npm you get whatever version is specified in the package.json file (in this case 4.9.5).

> On the other hand that might produce problems if your globally installed version does not match a required version. You could upgrade, but that might break other projects.

I think this is the real issue.  Typescript is already developer dependency.  So, it is already in node_modules (./node_modules/typescript/bin/tsc).  The project just isn't set up to use it by default.  Instead it is using whatever tsc you have lying around(assuming you don't have the node_modules/.bin dir in your path).

If you fire up npx, you get a shell that includes the binaries under node_modules/.bin.  Then you can execute any of the commands included from the shell.

Now that I think  about it changing the vscode task to use `npx tsc -b -w` is probably more direct.  No need to have npm run a script that runs tsc.  Just have npx run tsc with whatever options are needed.  That way it runs whatever tsc that is part of the project.

**Comment by chris-miner** [comment]
I updated my pull request to run tsc via npx instead.  That was a simpler change.

**Comment by mike-lischke** [comment]
That makes sense, yes. Thanks for the patch.

**Comment by chris-miner** [comment]
I noticed on a yo generated vscode extension that they run tsc as a npm script configured in the package.json file.  launch.json configures a prelaunch task of the 'default build task', which is defined in tasks.json as running an npm script named 'watch' which is set up in the package.json to run tsc.  So ... that is at least one common  approach.  So maybe running npx directly is not exactly standard.

**Comment by mike-lischke** [comment]
There are multiple ways to reach home, so npx might be as good as any other. Let's keep that for a while.
