### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by matthew-dean** [mike-lischke/vscode-antlr4#210]
I haven't been able to get the Antlr VSCode extension working.

It does static code analysis of the Lexer, but the Parser, even with a minimal file, returns: `RangeError: Maximum call stack size exceeded` in the Output window and as notifications in the VSCode window.

If I click on any of the Lexer tokens in the Antlr4 view or the Token Channels, or the Lexer Modes, VSCode pops up a notification `command '' not found`.

For the Parser Rules / Grammar Dependencies, and Actions & Predicates, (the parser view), it shows nothing, and continues just to popup `Maximum call stack exceeded`.

**Comment by matthew-dean** [comment]
Not sure if this helps, but the specific output in the Output window is:
```
RangeError: Maximum call stack size exceeded
	at Array.values (<anonymous>)
	at AntlrFacade.pushDependencyFiles ([redacted]/.vscode/extensions/mike-lischke.vscode-antlr4-2.3.1/out/src/backend/facade.js:285:33)
	at AntlrFacade.pushDependencyFiles ([redacted]/.vscode/extensions/mike-lischke.vscode-antlr4-2.3.1/out/src/backend/facade.js:288:22)
```

**Comment by matthew-dean** [comment]
Ohhhhh.... derp, I literally put
```
parser grammar CssParser;
options { tokenVocab = CssParser; }
```

The dependencies are circular, so yeah of course it would infinitely loop. Buuut you might want to detect infinite loops in dependencies so the extension doesn't crash while someone is writing?

**Comment by mike-lischke** [comment]
:-) nobody did that before so far, so this case wasn't relevant. Have to add a check there.

**Comment by matthew-dean** [comment]
@mike-lischke Yep, makes sense I would be the first to do something dumb 😆

**Comment by mike-lischke** [comment]
It think this will be helpful as well:

![Bildschirmfoto 2023-11-26 um 16 34 09](https://github.com/mike-lischke/vscode-antlr4/assets/2398704/5fef8d57-a295-413a-b391-68679cba6388)
