### ISSUE TITLE
`mode: internal` does not prevent code generation

### ISSUE THREAD

**Issue by matthew-dean** [mike-lischke/vscode-antlr4#211]
I have these settings in my VSCode settings.json file:
```
    "antlr4.generation": {
        "mode": "internal",
        "listeners": true,
        "visitors": true
    }
```
However, whenever I save a `.g4` file, it produces an `.antlr` directory in the same parent directory as my file, and generates an `.interp` / `.java` and `.tokens` file. Also, no matter what language is selected under `generation`, it outputs Java.

**Comment by mike-lischke** [comment]
I cannot reproduce the effect where always Java files are generated. Can you please test with the latest extension version? And for code generation: `internal` means: generate for internal use. If you don't want generated files at all, set the setting to `none`.
