### ISSUE TITLE
Missing README in VSCode and VS Marketplace

### ISSUE THREAD

**Issue by Ghost4Man** [mike-lischke/vscode-antlr4#220]
The extension description (`readme.md`) is missing from the extension page in VSCode (no _Details_ tab) and the [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=mike-lischke.vscode-antlr4) – it says _No overview has been entered by publisher_. 

I suspect this is due to `readme.md` being in `.vscodeignore`:
https://github.com/mike-lischke/vscode-antlr4/blob/7f96d9c920e37eaad2d850a658b6fcda59f56691/.vscodeignore#L14

**Comment by mike-lischke** [comment]
Oh gosh, I thought the missing readme on the marketplace was because it needed a bit time to get all files. Thanks for the heads up. I did a point release and hopefully the readme shows up soon.
