### ISSUE TITLE
Validation errors/warnings not visible to VS Code

### ISSUE THREAD

**Issue by zspitz** [mike-lischke/vscode-antlr4#23]
VS Code version: 1.21.0
Architecture: x64
Extension version: 1.3.0

I've opened the VB.NET grammar (from [here](https://github.com/dotnet/vblang/tree/master/spec) -- link at the bottom of the page). The ANTLR Exception output pane shows errors:

> warning(184): d:\Zev\Projects\vbnet-grammer\vb.g4:2274:0: One of the token XMLNameStartCharacter values unreachable. _ is always overlapped by token XMLNameCharacter
> warning(184): d:\Zev\Projects\vbnet-grammer\vb.g4:2274:0: One of the token XMLNameStartCharacter values unreachable. : is always overlapped by token XMLNameCharacter
> warning(184): d:\Zev\Projects\vbnet-grammer\vb.g4:2496:0: One of the token XMLNamespaceNameCharacter values unreachable. _ is always overlapped by token XMLNameCharacter
> warning(184): d:\Zev\Projects\vbnet-grammer\vb.g4:2496:0: One of the token XMLNamespaceNameCharacter values unreachable. _ is always overlapped by token XMLNameStartCharacter
> error(119): d:\Zev\Projects\vbnet-grammer\vb.g4::: The following sets of rules are mutually left-recursive [CCExpression, CCOperatorExpression] and [Expression, IsExpression, MemberAccessBase, DictionaryAccessExpression, InvocationExpression, IndexExpression, AdditionOperatorExpression, SubtractionOperatorExpression, MultiplicationOperatorExpression, FPDivisionOperatorExpression, IntegerDivisionOperatorExpression, ModuloOperatorExpression, ExponentOperatorExpression, RelationalOperatorExpression, LikeOperatorExpression, ConcatenationOperatorExpression, ShortCircuitLogicalOperatorExpression, LogicalOperatorExpression, ShiftOperatorExpression, XMLMemberAccessExpression, TypeExpression, MemberAccessExpression, OperatorExpression, ArithmeticOperatorExpression, DivisionOperatorExpression]

However, I don't see any of these errors in the Problems view, or inline in the editor.

**Comment by mike-lischke** [comment]
That's weird. I opened that grammar and immediately got a single warning, without doing anything:

![vb-grammar-warning](https://user-images.githubusercontent.com/2398704/37256846-9c328780-2560-11e8-8137-f81f9fd2ee66.png)

That also doesn't change when I edit the grammar and save it (to trigger a new generation run).

**Comment by zspitz** [comment]
I can confirm that I still don't see any errors even after editing and saving.

**Comment by zspitz** [comment]
I haven't changed the grammar. I can see the warnings (this is just the end of them) by opening the Output pane and choosing ANTLR Exception from the dropdown.
![image](https://user-images.githubusercontent.com/312166/37256977-61022994-256b-11e8-982e-dd64a93d1425.png)
