### ISSUE TITLE
Update to 2.4.2 broke project

### ISSUE THREAD

**Issue by c4lcifer** [mike-lischke/vscode-antlr4#231]
Hi,

after your newest update ( or maybe even before that ) my Code from my old antlr4 project wont run anymore.

As explanation:
Suddenly my code didnt work anymore and i couldnt figure out why. I didnt updated antlr4 or any other software that should be connected to this. I always used antlr version 4.9.2, This is where i coded all my lexers and parsers.

now i didnt paid a lot to attention on how the setup on the dev machine was working ( i didnt set that up, was already 3 years ago ) but I tracked the problem back to some error messages when i reinstalled everything. It seems you are now using another version of antlr4  ( 4.13.1 ) that comes from a package inside the antl4-cli directory. ( antlr4-4.13.2-SNAPSHOT-complete.jar )

Now my project wont work anymore at the moment and i cant figure out whats going on and why. Grammar checks show no errors in Lexer or Parser so my question, is it possible for you to provide a release before you switched to the new TypeScript runtime so that it is possible to roll back if theres a problem?

Sorry for tyhe sloppy explanation, im no dev expert in any means, and i dont know if theres a known problem here

**Comment by c4lcifer** [comment]
I I did some more digging and found out i run into a problem that quite some people have
[Could not deserialize ATN with version (expected 4) while using python age driver]

So it seems i run into this serialization problem when the antlr4 version from your new released is used. Still dont know how i can resolve this problem then though. 
Tried 2 other runtimes but didnt work

**Comment by mike-lischke** [comment]
You probably only need to upgrade your Python runtime to the latest version. Whenever a new ANTLR4 release comes out you very likely also have a new runtime to install.

**Comment by c4lcifer** [comment]
Hello,
I tried newest runtime. Didnt work. Can I manually Set another antlr4 Version in your plugin? Do I need to reverence another jar file then?

**Comment by c4lcifer** [comment]
Hello, how would i set that?
trying everything i can at the moment but cant seem to get it working with a different runtime. 

Is there somethig else that could influence this? Like Python or JDK version?

**Comment by c4lcifer** [comment]
I was able to find out the settings that still work for me:

- ANTLR4 grammar syntax support v2.3.1 ( antlr-4.9.2-complete.jar & antlr4-typescript-4.9.0-SNAPSHOT-complete.jar )
- antlr4-python3-runtime 4.9.3
- openjdk version "11.0.19" 2023-04-18

However, as said, when i upgrade your extension my code breaks with a deserialization error. Could not fix it with other python runtimes. I dont know if others have the same problem but my only solution for now is to stick with the old versions.

If you fiund this helpfull / want to look into it more im glad to help.

**Comment by mike-lischke** [comment]
Not a bug in the extension.
