### ISSUE TITLE
Cannot build .vsix

### ISSUE THREAD

**Issue by kaby76** [mike-lischke/vscode-antlr4#234]
I'm trying to build the .vsix of this extension. I cannot--without mods to package.json.

(Note: This is because I am trying to understand why this extension ignores the [outputDir setting](https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/extension-settings.md#parser-generation). It calls the tool to always generate files in the directory `.antlr/`, `[debug] Running Java with parameters: -jar c:\Users\Kenne\.vscode\extensions\mike-lischke.vscode-antlr4-2.4.2\node_modules\antlr4ng-cli\antlr4-4.13.2-SNAPSHOT-complete.jar -message-format antlr -o c:\msys64\home\Kenne\foobar\.antlr -listener -no-visitor -Xexact-output-dir c:\msys64\home\Kenne\foobar\Test.g4`. To do that, I want to build a .vsix file. I cannot run `code .`, and F5. It does not work properly. This is on Windows 11, node `v21.1.0`. The Antlr tool does not work in cmd.exe with disk drive rooted path names. See https://github.com/antlr/antlr4/issues/4463.)

In package.json, there is a script for ["package"](https://github.com/mike-lischke/vscode-antlr4/blob/95a2720d5dd9cc87203f59a650635e1657aa321f/package.json#L577). In a Bash shell, I type "npm run package". I get an error.
```
$ npm install
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.

added 583 packages, and audited 584 packages in 11s

113 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
11/08-08:40:36 ~/vscode-antlr4
$ npm run package

> vscode-antlr4@2.4.2 package
> vsce package

(node:7924) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Executing prepublish script 'npm run vscode:prepublish'...

> vscode-antlr4@2.4.2 vscode:prepublish
> npm run build


> vscode-antlr4@2.4.2 build
> tsc -b && esbuild ./src/extension.ts --bundle --outfile=out/main.cjs --external:vscode --format=cjs --platform=node --sourcemap=external --loader:.svg=file


  out\main.cjs      1.1mb ⚠️
  out\main.cjs.map  2.1mb

⚡ Done in 182ms
 ERROR  Extension entrypoint(s) missing. Make sure these files exist and aren't ignored by '.vscodeignore':
  extension/out/main.cjs.js
11/08-08:40:59 ~/vscode-antlr4
```
"npm run publish" produces a similar error.

#### Workaround
The command produces a .vsix if I change all the "main.cjs" to just "main.js" in package.json ([here](https://github.com/mike-lischke/vscode-antlr4/blob/95a2720d5dd9cc87203f59a650635e1657aa321f/package.json#L28) and [here](https://github.com/mike-lischke/vscode-antlr4/blob/95a2720d5dd9cc87203f59a650635e1657aa321f/package.json#L583)) -- because that's exactly what the compiler produces, a JavaScript file.

**Comment by mike-lischke** [comment]
You need a newer vsce. That was [a bug](https://github.com/microsoft/vscode-vsce/issues/824) which has been fixed a few months ago.

You cannot use .js as file extension because the vscode extension is now of type "module" and VS Code will automatically assume the main file is an ESM module (and fail to load it).

**Comment by kaby76** [comment]
Thanks. The fix required to run `npm install --force -g @vscode/vsce`, then retry.
