### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by amryounis** [mike-lischke/vscode-antlr4#237]
I noticed the following after adding the following formatting comments:

// $antlr-format off
// $antlr-format columnLimit 100
// $antlr-format indentWidth 8, tabWidth 8

- with or without any of the above formatting comments, right-click then format document => removes all actions in the document and leaves {} empty
- first formatting comment above just emptied the grammar file
- second formatting comment works fine after changing the limit number
- third comment has no effect. I tried each alone or in combination

![image](https://github.com/mike-lischke/vscode-antlr4/assets/3895133/46c8cf76-aafb-4791-a655-56e4a36ec6f0)
![image](https://github.com/mike-lischke/vscode-antlr4/assets/3895133/f0073e3f-feca-4404-85b5-061583494139)

**Comment by amryounis** [comment]
tabwidth and indentwidth do not work even from within the settings.json file

**Comment by mike-lischke** [comment]
There were some problems in the formatter package:

- Text retrieval for actions blocks was broken.
- Disabling formatting returned nothing.

For the indentation: these settings only have an effect if `useTab` is off (which was on by default). I changed this default to off.
