### ISSUE TITLE
How can I have my parser tree  graphical visualizations with my antlr grammar file and input for parse?

### ISSUE THREAD

**Issue by CBalaa** [mike-lischke/vscode-antlr4#241]

**Comment by CBalaa** [comment]
Something jusk like  antlr script in JetBrain IDE works, as following:

![image](https://github.com/mike-lischke/vscode-antlr4/assets/88538464/f5677c5f-b0eb-4b46-b322-91528068a07c)

**Comment by mike-lischke** [comment]
It's described in the [grammar debugging document](https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/grammar-debugging.md). You need to run an example using the debugger provided by the extension, which generates the parse tree and text as well as graphical output.

**Comment by CBalaa** [comment]
I got it. Thank you very much !
