### ISSUE TITLE
Visual parse tree not showing for version 2.4.5

### ISSUE THREAD

**Issue by sumesh107** [mike-lischke/vscode-antlr4#242]
I have been using the 'ANTLR4 View' vscode extension for the past 1 month in my Ubuntu 22.04. When debugging the grammar I had been using the parse tree visualizer, it used to show me the parse tree while debugging.

But since the upgrade to version 2.4.5 and a follow-up reload I realised my parse tree stopped visualizing. But when I returned to the previous version it's been working fine.  I am unsure if upgrading the dependency caused a bug or if I am missing something.

**Comment by mike-lischke** [comment]
This might be related to this [VS Code issue](https://github.com/microsoft/vscode/issues/196948). I see many of these "invalid debug adapter" messages in the VS Code dev console, when running vscode-antlr4 as normal extension. However, when debugging the extension then debugging in it works nicely.

**Comment by mike-lischke** [comment]
No, seems to be a packaging issue. I see that D3.js is not defined

**Comment by satabol** [comment]
I have the same problem. Windows 11, vscode 1.86.0, antlr-vscode plugin version 2.4.5.
If I try work just with vscode then I do not see anything on "Show ANTLR graph for rule":

https://github.com/mike-lischke/vscode-antlr4/assets/14288520/582e1406-9021-44d1-a07b-05a970be7af7

if I try start antlr-vscode in debug mode then I see anything:

https://github.com/mike-lischke/vscode-antlr4/assets/14288520/933efe32-fdf4-4f83-b1f1-1e76ef40288f

Also I have the same problem with "Show grammar call graph". It show nothing in ordinary vscode run and show "call graph" in debug mode. Also I update vscode to 1.86.1, disable all vscode plugins and restart vscode. 

May be this can help too?

**Comment by satabol** [comment]
It's now work good. Thank you.

**Comment by mike-lischke** [comment]
Thanks for your confirmation!
