### ISSUE TITLE
[Internal Error] Unhandled error message (code 50, message: syntax error: mismatched character '<EOF>' expecting ''' Please file a bug report at https://github.com/mike-lischke/vscode-antlr4/issues)

### ISSUE THREAD

**Issue by rabbittrix** [mike-lischke/vscode-antlr4#246]
The error message suggests that the parser is expecting a character that it's not finding before the end of the file (EOF). This often happens when there's a missing closing quote or bracket. However, in your code, all quotes and brackets seem to be properly closed.

This error might be a bug in the ANTLR plugin for Visual Studio Code. As the error message suggests, you should file a bug report at [https://github.com/mike-lischke/vscode-antlr4/issues](vscode-file://vscode-app/c:/Users/rabbi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html).

Before doing that, you can try to isolate the problem by commenting out parts of the code to see if the error persists. This might help you identify a specific part of the code that's causing the problem.

// Define tokens for field content
FIELD_CONTENT: (~['{', '}', '[', ']'] | '{{' ~['{'] ~['}']*)+;

I need help to fix the line!!!

**Comment by mike-lischke** [comment]
Keep in mind that character ranges don't need quotes. So it should be:

`FIELD_CONTENT: (~[{}[\]] | '{{' ~[{] ~[}]*)+;`

**Comment by rabbittrix** [comment]
You're right, thank you very much for your help, it worked perfectly.

**Comment by rabbittrix** [comment]
Can you help me on this:
COMPUTABLE_VARIABLE: '[' ~[\[\]]* ']';
BUSINESS_RULE: '[' ~[\[\]]* ']';

The problem is that the escape sequence [ is not valid in ANTLR. To fix this, you need to replace [ and ] with \[ and \] respectively.

**Comment by mike-lischke** [comment]
For general question please use Stackoverflow (www.stackoverflow.com).
