### ISSUE TITLE
[Feature Request] live tester

### ISSUE THREAD

**Issue by lublak** [mike-lischke/vscode-antlr4#252]
For now, it's just an idea.
In general, ANTLR can also generate a JavaScript file.
Couldn't this be used to offer a live tester?
Something like http://lab.antlr.org/ only in real time.
Here you could use the webview api: https://code.visualstudio.com/api/extension-guides/webview
This displays an html page that automatically integrates the previously generated javascript file from antlr.
On the page itself there is only an input field for testing. And another input field which contains the starting point.
The display then consists of a simple tree diagram: https://echarts.apache.org/examples/en/editor.html?c=tree-vertical

**Comment by mike-lischke** [comment]
Have you considered using [the debugger](https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/grammar-debugging.md)?

**Comment by lublak** [comment]
@mike-lischke i looked into it. It looks nice. But what about multiple inputs. It would be nice to quickly test some inputs on the fly. If you just try 20 inputs out:
Open the input.txt file write text. Open the antlr file, debug. Open the input.txt file write text. Open the antlr file, debug.  etc...

**Comment by lublak** [comment]
Another issue is, if you work with multiple grammas in the same project.
It doesn't work: 
![grafik](https://github.com/mike-lischke/vscode-antlr4/assets/44057030/eb1759ae-1e97-4f8a-b2f0-c9c8bb73db85)

**Comment by lublak** [comment]
Yes, I don't think there is a better solution. I'll close it here for now.
