### ISSUE TITLE
.interp files ignore specified output directory

### ISSUE THREAD

**Issue by GMMDMDIDEMS** [mike-lischke/vscode-antlr4#270]
On save of a grammar all target files are generated and stored by default in the `.antlr` folder. Defining another output directory all target files, except the `.interp` files, get stored in the specified output directory. The `.interp` files are still stored in the `.antlr` folder.

Is this intended behaviour? I am using `external` mode.

**Comment by mike-lischke** [comment]
Yes, this is the intended behavior. The files are still generated into that internal folder and afterwards the relevant files are copied to the target folder (in external mode). The .interp file is something only useful in special situations (like in this extension, which loads them to get an ATN for the parser/lexer interpreters).
