### ISSUE TITLE
issue in build in test that could be resolved as follows....

### ISSUE THREAD

**Issue by mlshort** [mike-lischke/vscode-antlr4#293]
I believe all you need to do is to update the package.json file as follows:

        "@typescript-eslint/parser": "8.0.0",

**Comment by mike-lischke** [comment]
@mlshort What build issues are you referring to? Can you provide a link please?

**Comment by mlshort** [comment]
The one from you main webpage here:

![BuildFailing](https://github.com/user-attachments/assets/7b3f47c6-2277-4be0-950e-a60f25b004a7)

**Comment by mlshort** [comment]
On my end, I have gotten it passed that ....

![BuildAndTest](https://github.com/user-attachments/assets/dec72b96-738e-4d40-a284-ed5517eca82b)

**Comment by mlshort** [comment]
Although, after running lint, I think there are other dependencies that need updating as well....

![Dependencies](https://github.com/user-attachments/assets/0c0ed717-19ee-4b20-be13-0441fea9a5c1)

**Comment by mike-lischke** [comment]
Ah, I forgot to look after that. Again a module upgrade broke the build. I've seen this quite often in the recent past in various projects. That's also why I don't use the "^" modifier anymore.

**Comment by mike-lischke** [comment]
And watch out: the extension no longer uses antlr4ts.

**Comment by mlshort** [comment]
Very good.  I think I read an outdated document that suggested that antlr4ts was needed.

I will remove.

I have also been working to migrate "Semi", "Indent" over to using the Stylistic plugin.

see - https://eslint.style/guide/getting-started

However, am I not 100% confortable with all of my local changes just yet until I run some more tests.

**Comment by mlshort** [comment]
> Ah, I forgot to look after that. Again a module upgrade broke the build. I've seen this quite often in the recent past in various projects. That's also why I don't use the "^" modifier anymore.

FYI - I did not manually add any of the "^" modifiers myself.

I believe these were auto-updated after running commands such as:

`npm i -D @stylistic/eslint-plugin`

I suppose I can manually remove them if they are not recommended or needed.

**Comment by mike-lischke** [comment]
Fixed by patch 51dacf6
