### ISSUE TITLE
Various Lint Issues

### ISSUE THREAD

**Issue by mlshort** [mike-lischke/vscode-antlr4#294]
This is an effort to share some of the Lint issues encountered and local fixes made to address.

1. Extra instruction as follows:

FrontEndUtils.tx(250):
            const info = backend.getContextDetails(document.fileName); **1;**

**Comment by mlshort** [comment]
You are correct.

Was not sure you wanted me working directly on your code or not.

:)

**Comment by mlshort** [comment]
Ok, I have all of the lint errors addressed locally.  Only some warnings remain.  Will do a PR for your review.

![LintWarnings](https://github.com/user-attachments/assets/0360a349-2477-4266-855d-0f28b9912580)

**Comment by mike-lischke** [comment]
Addressed by #51dacf6cc87509708df06dc30de8ffc39a70536f
