### ISSUE TITLE
Debugger won't work when using 'external' mode

### ISSUE THREAD

**Issue by littleEndianOne** [mike-lischke/vscode-antlr4#30]
When I set mode to 'external' to generate JavaScript output I have to manually copy the .interp files into the .antlr folder to get the debugger to run. Without the the files in the .antlr folder I get the following error message when trying to run the debugger.
![errormessage](https://user-images.githubusercontent.com/38173402/38463192-724ff808-3b27-11e8-88c2-b37072456fab.png)
I'm using version 2.0.2.

**Comment by mike-lischke** [comment]
Maybe [the copy opertion fails](https://github.com/mike-lischke/vscode-antlr4/blob/master/src/extension.ts#L370)? I recently had to fix something there to avoid trouble when the output folder is set to `.antlr`.

**Comment by tekord** [comment]
I got the same error.
