### ISSUE TITLE
Lombok can't parse this source: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by RoelVdP** [mike-lischke/vscode-antlr4#313]
Not a bug report, but rather a "howto" for anyone searching for this error. As such, feel free to close as resolved immediately.

If you get an error like this:
```
Lombok can't parse this source: java.lang.StackOverflowError
```
Then do this:

In Visual Studio Code click: File > Preferences > Settings > Search for "java.jdt.ls.vmargs" and click "Edit in settings.json" > In the file change this indented line:
```
"java.jdt.ls.vmargs": ""
```
To read instead:
```
"java.jdt.ls.vmargs": "-Xss4m"
```
And save. The reopen Visual Studio Code. This will stop the error from happening. Basically, there is a StackOverflowError likely due to deep recursion or large call stacks, and this increases the thread stack size to 4 megabyte per thread.

**Comment by mike-lischke** [comment]
Thanks @RoelVdP. How is this related to the ANTLR4 extension?

**Comment by RoelVdP** [comment]
Ah, I see. My mind unconsciously had the two connected. Thinking about it, they could or could not be.
