### ISSUE TITLE
Adding support for templates and C# namespaces

### ISSUE THREAD

**Issue by WXAGames** [mike-lischke/vscode-antlr4#316]
I like to organize my code and noticed that this extension doesn't seem to allow specifying a namespace for generation or even templates to hack around that. Since these are already supported in ANTLR, I figure it shouldn't be very difficult to add.

**Comment by mike-lischke** [comment]
What about the `package` value in the [extension settings](https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/extension-settings.md#parser-generation)?

**Comment by WXAGames** [comment]
Ah! I apparently didn't see that when looking for this. Maybe it should be given a default value of null or an empty string to be more obvious? Thank you though!
