### ISSUE TITLE
Issue using C#

### ISSUE THREAD

**Issue by bnjepsen** [mike-lischke/vscode-antlr4#34]
Hi,
I'm having an issue using the nuget Antlr4 version 4.6.5-beta002 with the extension. I think it's due to a version mismatch. The extension seems to be generating code for antlr 4.7.2.

![image](https://user-images.githubusercontent.com/6596647/39555297-82b9ecc6-4e78-11e8-98cb-0197e205f117.png)

**Comment by mike-lischke** [comment]
Have you tried to use the latest C# runtime from Github?

**Comment by bnjepsen** [comment]
Yep, works fine now :) can you set the namespace for the generated files?

**Comment by mike-lischke** [comment]
There's a [package](https://github.com/mike-lischke/vscode-antlr4#parser-generation-1) paramater for that.

**Comment by andrewsav-datacom** [comment]
@bnjepsen but 4.6.5-beta002 _is_ the latest runtime from github!!! How did you get this resolved?

**Comment by Thaina** [comment]
I think you should put this package in the document

https://www.nuget.org/packages/Antlr4.Runtime.Standard/

Current Antlr4 package still 4.6.6
