### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by tekord** [mike-lischke/vscode-antlr4#35]
Hi! Thanks for nice extension. But I have some issues with it. The most important for me now is not working debugger. It worked earlier, but I edited launch configuration and VS showed me the error: "Debug adapter process has terminated unexpectedly". I returned my launch configuration back, but it didn't help. My current launch configuration is:
```
        {
            "name": "ANTLR",
            "type": "antlr-debug",
            "request": "launch",
            //"input": "${workspaceFolder}/${command:AskForTestInput}",
            "input": "tests/input.qs",
            "grammar": "QaterParser.g4",
            "startRule": "program",
            "printParseTree": true, // I removed this line when I got the error in first time
            "visualParseTree": true
        },
```

My workspace config is the following:

```
    "antlr4.generation": {
        "mode": "internal",
        "outputDir": "generated",
        "language": "Cpp", // I know this is not used when mode is 'internal'
        "listeners": false,
        "visitors": true
    },
```

**Comment by tekord** [comment]
Oh, i disabled all C++ and C# extensions, restarted VS and the error is gone.

**Comment by mike-lischke** [comment]
Hmm, so it seems some other extension has side effects? You could try to enable them back, one by one, to find out what the real culprit is. In any case I guess we can close this issue, right?

**Comment by mike-lischke** [comment]
Has this issue been resolved?

**Comment by linonetwo** [comment]
Same on me, my launch.json:
```json
{
  "version": "2.0.0",
  "configurations": [
    {
      "name": "antlr4-tokenRegexIt",
      "type": "antlr-debug",
      "request": "launch",
      "input": "examples/literal.txt",
      "grammar": "TokenRegexIt.g4",
      "startRule": "query",
      "printParseTree": true,
      "visualParseTree": true
    }
  ]
}
```
setting.json
```json
{
  "antlr4.generation": {
    "mode": "external",
    "language": "JavaScript",
    "outputDir": "./src/antlrGeneratedParser",
    "listeners": true,
    "visitors": true
  },
  "antlr4.referencesCodeLens.enabled": true
}
```

**Comment by linonetwo** [comment]
Solved, my fault, I didn't noticed that "startRule" means the rule in `.g4` file. I thought It was a vscode task setting.
