### ISSUE TITLE
Parse Tree Visualization not showing

### ISSUE THREAD

**Issue by TheGenezis** [mike-lischke/vscode-antlr4#38]
Hello Mike,

I love your extension and its absolutely genius, however I already struggled a bit with making it work even on a dummy test project and I cannot get a graph visualization or cannot find the way how to invoke / trigger it in VS.

Took mi already few hours to translate "open via context menu of IDE" to 3 dots in the end of open files tab, there I found the Railroad diagram, but not the ParseTree Graph.

Also I am getting print tree correctly in Debug Console so probably only the case of finding how to show it in VS Code?

Config should be alright:
        {
            "name": "antlr4",
            "type": "antlr-debug",
            "request": "launch",
            //"input": "${workspaceFolder}/${command:AskForTestInput}",
            "input": "input.txt",
            "grammar": "Expression.g4",
            "startRule": "startWithEOF",
            "visualParseTree": true,
            "printParseTree": true
        }

Best regards,
Simon

**Comment by mike-lischke** [comment]
The parse tree cannot be shown using the editor context menu like the railroad diagrams, the call graph or the ATN graph. Instead it shows up only after you finished a debug run (because only then a tree is generated). Read the [Debugging](https://github.com/mike-lischke/vscode-antlr4#debugging) section in the readme again. It's all explained there.

**Comment by TheGenezis** [comment]
First of all thank you for your time.
I read the readme, several times and I am successfully running it and getting parse tree printed in console (which I suppose have same print logic and conditions as js Tree) and still nothing.
But I am running only debug (or even start with debug and still nothing) on *.g4 file, isnt one of those thinks an issue? (like I have to run c# file creating the grammar etc).

Also I will add up temp picture ( https://ctrlv.cz/3hYD )

**Comment by mike-lischke** [comment]
Hard to say what's wrong. Since you have both trees enabled and the textual version shows up, also the graphic tree should be shown. You don't get at least an empty parse tree tab? If no tab comes up there might be a problem that prevents to show it. Can you look in the vscode "Developer Tools" (see Help menu) to see if there's an error message? Also, is anything shown in the vscode console tab?

**Comment by TheGenezis** [comment]
I got something from DevTools, but I and not able to tell if it might be causing an issue, also looks like not an error from my side, can you confirm please?

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1311   ERR [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character: Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:45:689
	at t.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:45:1003)
	at new t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:47:756)
	at t.e.with (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:46:715)
	at Object.getTextProviderUri (C:\Users\Simone\.vscode\extensions\mike-lischke.vscode-antlr4-2.0.3\out\src\frontend\TextContentProvider.js:85:20)
	at GrapsDebugger.debugger.on (C:\Users\Simone\.vscode\extensions\mike-lischke.vscode-antlr4-2.0.3\out\src\frontend\AntlrDebugAdapter.js:264:94)
	at emitNone (events.js:86:13)
	at GrapsDebugger.emit (events.js:188:7)
	at Immediate._ (C:\Users\Simone\.vscode\extensions\mike-lischke.vscode-antlr4-2.0.3\out\src\backend\GrapsDebugger.js:261:18)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by mike-lischke** [comment]
Dealing with this issue in #37.

**Comment by TheGenezis** [comment]
Works like a charm now! Thanks for your time and keep the good work up!
