### ISSUE TITLE
Export Call Tree also with "interactive highlights" not only as static SVG

### ISSUE THREAD

**Issue by TheGenezis** [mike-lischke/vscode-antlr4#40]
Hello Mike,

I was wandering if there is any way how to export Parse Tree with that "interactive highlights" (when hovering above categories nodes) as now if I am correct it "only" (very impressive and cool regardless) as static SVG. Is there at least any way how to hack it in any way or form into at least half decent format (I assume combination of js and html is in place right now)

Thanks for any help!

**Comment by mike-lischke** [comment]
For the interactive view you would need to export the entire HTML, which is possible, but would need to be implemented. The interactivity comes from Javascript, running in the background (and SVG doesn't support that).

If you are into JS anyway and want more customization just look in the [call-graph.js file](https://github.com/mike-lischke/vscode-antlr4/blob/master/misc/call-graph.js).
