### ISSUE TITLE
Lexer grammar ignored + debug not working

### ISSUE THREAD

**Issue by GabrieleFrau** [mike-lischke/vscode-antlr4#46]
ctdLexer.g4
```
lexer grammar ctdLexer;
DOT: '.';
```
ctdParser.g4
```
parser grammar ctdParser;
main: DOT;
```
it always says: 

> warning(125): c:\Users\\*******\test\grammar\ctdParser.g4:2:6: implicit definition of token DOT in parser

```
{
    "version": "2.0.0",
    "configurations": [
        {
            "name": "test",
            "type": "antlr-debug",
            "request": "launch",
            "input": "input.txt",
            "grammar": "grammar/ctdParser.g4",
            "startRule": "main",
            "printParseTree": false,
            "visualParseTree": false,
            "windows": {
                "trace": false
            }
        }
    ]
}
```
debugging throws this error: 

> Error while launching debug session: TypeError: Cannot set property 'inputStream' of undefined

Am i missing something?

**Comment by GabrieleFrau** [comment]
My bad: I was missing the `options { tokenVocab=ctdLexer; }` directive

**Comment by mike-lischke** [comment]
However, in that case the error message should be clearer. Without tokenvocab you shouldn't be able to generate your parser + lexer classes (there should be a message from ANTLR). And the debug adapter should just show a message that the interpreter data could not be generated.

**Comment by mike-lischke** [comment]
Will be improved with the next release.

**Comment by phanirithvij** [comment]
@mike-lischke I'm a beginner to antlr and I think it makes sense to have a clear explanation here.
