### ISSUE TITLE
Not possible to use ${} macros in launch.json

### ISSUE THREAD

**Issue by cprieto** [mike-lischke/vscode-antlr4#48]
Currently, with `input` and `grammar` entries in `launch.json` you cannot use `${}` variables, for example, the following sample:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "antlr4",
      "input": "${workspaceFolder}/${command:AskForTestInput}",
      "type": "antlr-debug",
      "request": "launch",
      "grammar": "Data.g4",
      "startRule": "${command:AskForTestInput}",
      "printParseTree": true,
      "visualParseTree": true
    }
  ]
}
```

will fail with:

```
Cannot read test input file:
[some directory]/${workspaceFolder}/${command:AskForTestInput}
```

The same is for `grammar` while `startRule` works perfectly, for example, this launch configuration will work:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "antlr4",
      "input": "test.data",
      "type": "antlr-debug",
      "request": "launch",
      "grammar": "Data.g4",
      "startRule": "${command:AskForTestInput}",
      "printParseTree": true,
      "visualParseTree": true
    }
  ]
}
```

I tried with `${file}` and similar, but it looks like `grammar` and `input` are not preprocessing macros.

Tested in version v2.0.4

**Comment by ronnieoverby** [comment]
The link you provided when you stated that variable substitution in launch.json has been removed doesn't say that.

It says:

> Variable substitution in **package.json** will no longer be supported

So, why doesn't variable substitution in launch.json work for input file?

**Comment by mike-lischke** [comment]
Variable substitution stopped working suddenly without any changes from my side in this area. So I concluded the mentioned change does not only apply to package.json but all json files. I also read somewhere that it was never meant to work and to my knowledge this feature had no documentation. I only used it because I saw it in one of the debugger examples.

**Comment by ronnieoverby** [comment]
That's unexpected because it's documented well here: https://code.visualstudio.com/docs/editor/debugging#_variable-substitution

**Comment by mike-lischke** [comment]
Interesting, seems that documentation has been added meanwhile. But then I wonder why macro substitution stopped working at that time. I'll take another look.

**Comment by ronnieoverby** [comment]
I wonder if the configuration property needs to opt in to variable substitution somehow. 🤔
