### ISSUE TITLE
Semantic predicates are not behaving correctly

### ISSUE THREAD

**Issue by cprieto** [mike-lischke/vscode-antlr4#49]
This is a weird issue, when using semantic predicates, the generated grammar behaves incorrectly in debugging mode, a good example from the ANTLR4 book:

```antlr
grammar Data;

file: group+;
group: INT sequence[$INT.int];

sequence[int n]
	locals[int i = 1;]: ( {$i<=$n}? INT {$i++;})*;

INT: [0-9]+;
WS: [ \t\n\r]+ -> skip;
```

Running against this sample data:

```
1 23 3 6 8 4
```

Against antlr4 tools (4.7.1) returns correctly:

![antlr4_parse_tree](https://user-images.githubusercontent.com/94194/45888948-8e622500-bdbf-11e8-9057-f14086f57ba2.png)

But the same parse tree is incorrect in VSCode ANTLR4:

![screen shot 2018-09-21 at 17 24 36](https://user-images.githubusercontent.com/94194/45890440-3fb68a00-bdc3-11e8-9452-cc0832a19fa2.png)

I think it has something to do with ANTLR binaries, because if I try the same in latest [IntelliJ ANTLR4 plugin](https://github.com/antlr/intellij-plugin-v4) (version 1.8.4) I see the same invalid tree:

![screen shot 2018-09-21 at 17 29 01](https://user-images.githubusercontent.com/94194/45890687-ddaa5480-bdc3-11e8-83c7-f80d9bb0130e.png)

**Comment by mike-lischke** [comment]
Please read the [readme.md](https://github.com/mike-lischke/vscode-antlr4/blob/master/README.md), section [Limitations](https://github.com/mike-lischke/vscode-antlr4/blob/master/README.md#limitations).
