### ISSUE TITLE
Kalyan

### ISSUE THREAD

**Issue by kalyank23** [mike-lischke/vscode-antlr4#54]
Hi,

I am going through your tutorial. and able ti view the parse tree and save to .svg file, but the thing is that for larger graphs of around 300 nodes, I am not able to save complete graph to .svg file and also the the horizontal bar is not available to drag the graph. Could you let me know if this is supported.

https://marketplace.visualstudio.com/items?itemName=mike-lischke.vscode-antlr4#overview

**Comment by mike-lischke** [comment]
When you click on a free place in the graph you can drag it around to see more parts of it. With you mouse wheel or the trackpad you can change the zoom level and so view details or the entire graph.
