### ISSUE TITLE
golang: lexer generated, parser and listener missing?

### ISSUE THREAD

**Issue by Lercher** [mike-lischke/vscode-antlr4#55]
Hi all

This is probably something for the documentation or even worth a new diagnostic message. I noticed under Linux that the grammar stored in the file `sparql.g4`

````antlr4
grammar Sparql;
...
````

with `antl4.generation.mode external` would generate the file `sparql_lexer.go` but not the expected `sparql_base_listener.go  sparql_listener.go  sparql_parser.go`. No diagnostic messages.

Solution: renaming the file to `Sparql.g4` produced all expected files. Note the capitalized `S` in the filename instead of `s`.

**Comment by mike-lischke** [comment]
Hi Martin, I guess this is a problem of the Go target. You probably can also reproduce that by manually running antlr4.jar. Better report that in the main ANTLR4 repo, so that it gets fixed.
