### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by xied75** [mike-lischke/vscode-antlr4#58]
Not sure current formatting settings cover this:

```antlr
fragment UnicodeClassND:
	'\u0030' ..'\u0039'
	| '\u0660' ..'\u0669'
	| '\u06f0' ..'\u06f9'
```
After formatting, there is space added before the two dot ```..```

What if we want to adjust this: NoSpace, BothSide, Left, Right, something like these.

**Comment by mike-lischke** [comment]
Closing, will be handled as part of the new antlr-format package.
