### ISSUE TITLE
How to show ATN Graph?

### ISSUE THREAD

**Issue by xied75** [mike-lischke/vscode-antlr4#6]
On Windows 10 I selected a rule from a parser g4 file, and right click to fire "Show ATN ...", but got "No ATN data found (code generation must run at least once in internal or external mode)"

I do understand this message, but how do I run the code gen?

**Comment by mike-lischke** [comment]
Easy, with default settings you just need to save your grammar once. The default mode is set to "internal", so it should do the generation then. You should see a little animation in the left part of the status bar while generation is in progress (most of the time it's very quick, unless you have a big grammar).

**Comment by xied75** [comment]
Yes I can see that progress icon, pretty busy forever. And there is a .antlr folder created, but nothing there. Do I need to install antlr tooling somewhere? Or is it installed by the extension? Where can I find it? Was it a .exe? Do I need to have Java runtime installed?

**Comment by mike-lischke** [comment]
Hmm, that's interesting. Yes, you need Java on your box, available on your PATH. Seems I must add a check for that. The antlr jars are included in a sub module (see node_modules/antlr4-graps/antlr).

**Comment by xied75** [comment]
Got you, I have been wondering why there is an Equalizer showing, I thought it was because I'm listening to some music. So in theory if there is an Antlr Runtime in nodejs then it will fully standalone right?

**Comment by mike-lischke** [comment]
:-) equalizer, no, probably the animation wasn't stopped because of an error.

And yes, the extension should fully work autonomously (except for the Java installation).

**Comment by mike-lischke** [comment]
Could you solve your problem or is there anything I can do here?

**Comment by xied75** [comment]
Work item for you to check JRE exists? Closing...
(thanks for the quick reply)
