### ISSUE TITLE
Error while launching debug session: start rule "Hello" not found

### ISSUE THREAD

**Issue by kevinfay** [mike-lischke/vscode-antlr4#61]
VS Code 1.30.1
vscode-antlr4 2.1.1
I have a simple g4 grammar
```ANTLR
grammar Hello; // Define a grammar called Hello
r : 'hello' ID ; // match keyword hello followed by an identifier
ID : [a-z]+ ; // match lower-case identifiers
WS : [ \t\r\n]+ -> skip ; // skip spaces, tabs, newlines, \r (Windows)
```
and I put the configuration in the workspace 

```JSON
 {
    "launch": {
        "version": "2.0.0",
        "configurations": [
        {
            "name": "antlr4-Hello",
            "type": "antlr-debug",
            "request": "launch",
            "input": "Hellotest/input.txt",
            "grammar": "Hello.g4",
            "startRule": "Hello",
            "printParseTree": true,
            "visualParseTree": true
        }
    ]
    },
    "antlr4.generation": {
        "mode": "internal",
        "language": "Java",
        "listeners": true,
        "visitors": true
    }
}
```

when i changed and saved the Hello g4 file, I got the busy animation and entered the ./.antlr/ directiory
found the generated six files included "**Hello.interp HelloLexer.interp HelloLexer.tokens Hello.tokens HelloLexer.java HelloParser.java**"

then when I satrt the debug, I got the error
Is there something wrong about my configuration?
It seems like the auto generation didn't run the javac, so the class files are missing?
tks

**Comment by mike-lischke** [comment]
Launch configuration and vscode preferences are 2 separate things. The "antlr4.generation" setting must be in the vscode user settings, not in a launch config.

And a start rule `Hello` would imply a lexer rulle (first char is a capital letter). However, lexer grammars cannot be debugged. In your parser the entry rule is obviously `r`, so you should set that as your start rule.

**Comment by mike-lischke** [comment]
@kevinfay Did my advice help you with your problem or do you have another related question?

**Comment by kevinfay** [comment]
Yes! It’s woriking...
but I was still confused by the ATN graphs
It did not show up
