### ISSUE TITLE
GraphViz dot

### ISSUE THREAD

**Issue by flip111** [mike-lischke/vscode-antlr4#64]
Would be nice to show grammar as graph with nodes and eges. Easy to see recursive sections that way.

**Comment by mike-lischke** [comment]
Do mean this:

![](https://github.com/mike-lischke/vscode-antlr4/raw/master/images/antlr4-4.png)

? Read more about that [in the documentation](https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/graphical-visualizations.md#atn-graphs).

**Comment by flip111** [comment]
@mike-lischke both diagrams don't seem to be recursive, but grammar can be recursive. More like screenshot "Decision DFA Visualization" on https://www.antlr3.org/works/

**Comment by mike-lischke** [comment]
Well, I haven't taken a sshot of a recursive rule, but I can promise you this is also shown in vscode if you select such a rule. Keep in mind that internally, direct left recursive rules are converted to an ATN graph with no left recursion.

**Comment by flip111** [comment]
Thanks Mike. For the ATN graph I had to execute the grammar. Not sure what
is meant by that. I'm unfamiliar with vscode as I installed it just for
this extension

**Comment by mike-lischke** [comment]
Is anything else needed here or can I close this issue?

**Comment by flip111** [comment]
Let's close it for now
