### ISSUE TITLE
Can't get debugger to work

### ISSUE THREAD

**Issue by MishaBeek** [mike-lischke/vscode-antlr4#65]
Hi,

I know a similar issue has been posted, but that does not seem to cause of my problem.
I have set up the following launch file:

`{
    "version": "2.0.0",
    "configurations": [
        {
            "name": "Debug ANTLR4 grammar",
            "type": "antlr-debug",
            "request": "launch",
            "input": "MyParser/example1.sql",
            "grammar": "MyParser/src/main/java/org/parser/MyParser.g4",
            "startRule": "statement",
            "printParseTree": true,
            "visualParseTree": true
        }
    ]
}`

When starting the debug with F5 I get an error message: 'typeerror cannot set property 'inputstream' of undefined'

Both the grammar file (combined) and the input file exist. The startRule also exists in the grammar. I just trying to locate the cause of this issue. I am using VsCode on Windows 10.

Any advice/guidance is appreciated.

Thanks,

Misha

**Comment by mike-lischke** [comment]
Have you enabled parser generation and saved your grammar at least once?

**Comment by MishaBeek** [comment]
I think I did (how can I double check).

In the mean time I am separating the Lexer from the Parser, which does allow me to run the debugger.
This generates a lot of other issues, but these are unrelated.

**Comment by mike-lischke** [comment]
The default for parser generation is `internal` which saves all the generated file (and most important: the interpreter data) in the subfolder `.antlr` of your workspace folder. See there if you have the `. interp` file for your grammar. Debugging is not possible without this file.

**Comment by mike-lischke** [comment]
Anything I can do here yet? If not I'll close the issue.
