### ISSUE TITLE
How do I find all occurences of a symbol?

### ISSUE THREAD

**Issue by kaby76** [mike-lischke/vscode-antlr4#68]
I opened a grammar file and right-clicked on a symbol in a rule, which could be a terminal (LHS symbol of lexer rule) or non-terminal (LHS symbol of parser rule). A drop-down menu appears, and I can click on "Go to definition" to navigate to the rule defining the symbol. But, the complementary of a find of the defining occurrence of a symbol is to find all applied occurrences of a symbol, ie, a smart find that looks for all occurrences of a symbol on the RHS of a rule. An important feature of an editor for a language is to find all occurrences of a symbol. As an example, open VS IDE and open a large program, and right-click on a variable, and look for "Find All References". A simple find (menu bar|Edit|Find) works fine for finding occurrences of a sequence of characters works for now, but you should have a "Find all applied occurrences" or "Find all occurrences" item in the pop-up context menu for symbols. Note, it should not just highlight the symbol, but result in a list I can use for navigation, just like the standard find function in the editor. (Version 2.1.1)

**Comment by mike-lischke** [comment]
Implemented in 113bd63d0726552a27625dab48ef64671fb017a0
