### ISSUE TITLE
How can I pass command line arguments to antlr?

### ISSUE THREAD

**Issue by BrentRector** [mike-lischke/vscode-antlr4#69]
For example, my *.g4 file contains UTF-8 characters. Therefore I need to invoke antlr with the -encoding command line option such as:

antlr4 -encoding utf8 grammar.g4

I suspect the vscode extension doesn't pass that command line option as copile-on-save produces errors in VSCode but not when running antlr from the command line. However, I cannot find a configuration setting for the encoding command line option.

Similarly, I need to pass the encoding option when invoking grun as well.

**Comment by mike-lischke** [comment]
No, currently it's not possible to specify command line parameters. This can be added as an addition to the launch task.

**Comment by kenjiuno** [comment]
Hi.

Can I pass 2 or more parameters to `additionalParameters`?

I want to pass `-encoding UTF8`.

In `.vscode/settings.json`

```json
{
    "antlr4.generation": {
        "additionalParameters": "-encoding UTF8",
        "mode": "internal",
        "language": "Java",
        "listeners": true,
        "visitors": false
    }
}
```

However output from generator is:

```
error(2):  unknown command-line option -encoding UTF8
```

I have looked up b0f7ebdf647b6c6b1408e00574546526617e8ec7.

https://github.com/mike-lischke/vscode-antlr4/blob/62e36149c2e4dafe875a9547db1ea5baf73b7b2a/src/backend/SourceContext.ts#L1075-L1077

`options.additionalParameters` isn't separated.

Perhaps passing `-encoding UTF8` will give `"-encoding UTF8"` in command line args.

```bat
%JAVA_HOME%\bin\java -jar H:\DL\antlr-4.10.1-complete.jar "-encoding utf8" Zengin.g4
error(2):  unknown command-line option -encoding utf8
```

The above error message matches.

I want to pass separated parameters like this:

```bat
%JAVA_HOME%\bin\java -jar H:\DL\antlr-4.10.1-complete.jar -encoding utf8 Zengin.g4
```
