### ISSUE TITLE
Generate visitors

### ISSUE THREAD

**Issue by notsonotso** [mike-lischke/vscode-antlr4#7]
Plugin looks great.

How do I

1. Set the output path? The ".antlr" directory doesn't work well with my webpack setup, I need to place the sources under "../src"

2. How do I configure it to generate Visitor and Listener interfaces?

Thanks!

**Comment by mike-lischke** [comment]
Have you read the readme.md? It contains descriptions for all possible settings. In particular `antlr4.generation.outputDir` is what you need, but also `antlr4.generation.visitors` and `antlr4.generation.listeners` are useful.

**Comment by notsonotso** [comment]
@mike-lischke new to extension. Where to I put "antlr4.generation.outputDir" etc?

**Comment by mike-lischke** [comment]
https://code.visualstudio.com/docs/getstarted/settings, vscode will give you completion also for settings. Search for antlr on the left hand pane where all the available options are listed.

**Comment by notsonotso** [comment]
@mike-lischke Changing settings doesn't work. Still no output directory change, nor any lister or visitor generated.

Settings:

{
    "antlr4.generation.visitors": true,
    "antlr4.generation.listeners": true,
    "antlr4.generation.outputDir": "src/antlr"
}

**Comment by notsonotso** [comment]
Oh, for fucks sake,

    "antlr4.generation.mode": "external"

...why isn't this external by default? Nothing got exported to my "outputDir" without this.

**Comment by mike-lischke** [comment]
This is what I documented. Why doing the extra rounds if no generated code is required? However, I'm open to wishes. If there's a significant part of the user base that prefers having the external mode on by default this can be changed.

**Comment by notsonotso** [comment]
Can't imagine the usecase for not generating listeners or visitors.
