### ISSUE TITLE
help

### ISSUE THREAD

**Issue by maodou38** [mike-lischke/vscode-antlr4#70]

**Comment by maodou38** [comment]
i have a old version .g4 which has rule: EMPTY : '';

**Comment by maodou38** [comment]
BUT I CAN'T RUN WITH YOUR TOOLS,it gives me a error:string literals and sets cannot be empty: ''.there has any idea to solve it？

**Comment by mike-lischke** [comment]
Please ask general ANTLR4 questions on Stackoverflow.
