### ISSUE TITLE
not all features available

### ISSUE THREAD

**Issue by amryounis** [mike-lischke/vscode-antlr4#72]
Hi,
after installing, via VSC directly, the antlr (extension) icon is not showing in the action bar. also I cannot start debugger for missing any suitable configuration

**Comment by mike-lischke** [comment]
The ANTLR4 action section is not yet released. I only updated the documentation already. But I hope I can soon do the release. If you then find something not working please open a new issue.

**Comment by mike-lischke** [comment]
Actually, I didn't document the new section yet. Where did you get the information it would be available?
