### ISSUE TITLE
Suggestion: Give a choice to choose either auto generate codes nor manually generate.

### ISSUE THREAD

**Issue by XunGong99** [mike-lischke/vscode-antlr4#73]
I have a related g4 file, but it is used as a reference. How ever, if I try to open it, the extension will automatically generate parser and lexer which I do not need. If there is a choice whether the file will be auto generated, that's awesome.

**Comment by mike-lischke** [comment]
There is such an option, but only for all grammar files. How would you expect a per-file setting to look like? Could be tricky to specify it in the settings.

**Comment by XunGong99** [comment]
It would be better if I can choose some files not to generate automatically.
give a settings.json option "antlr4.autogenreatefile" or
