### ISSUE TITLE
Debugging breakpoints are ignored

### ISSUE THREAD

**Issue by brikken** [mike-lischke/vscode-antlr4#74]
I've set a breakpoint in my grammar, but debugging (F5) doesn't stop execution at the breakpoint. It simply continues right to the end and produces the parse tree.
![image](https://user-images.githubusercontent.com/17687681/54632572-b684c500-4a7e-11e9-918e-6619b3ca6385.png)

Grammar
```
grammar Test;

program: id*;
id: ID;

ID: [a-zA-Z]+;
WS: [ \t\r\n]+ -> skip;
```
launch.json
```
{
    "version": "2.0.0",
    "configurations": [
        {
            "type": "antlr-debug",
            "request": "launch",
            "name": "antlr4",
            "input": "input.txt",
            "grammar": "Test.g4",
            "startRule": "program",
            "printParseTree": true,
            "visualParseTree": true
        }
    ]
}
```
In addition, I have to specify the "grammar" and "startRule" elements for debugging to even work, even though the grammar file is active in the editor.

input.txt
```
abc cde
abc cde
```
Folder with grammar
![image](https://user-images.githubusercontent.com/17687681/54632517-90f7bb80-4a7e-11e9-9215-29853d4bd5aa.png)

VS Code
```
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```
Latest version of the extension (just installed)

**Comment by sipian** [comment]
I am facing the same issue in Ubuntu Linux. Breakpoints are being ignored.
vscode version: 1.33.1
Linux Kernel: x64 4.15.0-47-generic

**Comment by solartes** [comment]
![image](https://user-images.githubusercontent.com/22583659/65643917-7b78c680-dfb8-11e9-8e2d-f8876de88829.png)

**Comment by solartes** [comment]
Same problem to me
![image](https://user-images.githubusercontent.com/22583659/65643953-90555a00-dfb8-11e9-8dec-9805785acaa9.png)

**Comment by mike-lischke** [comment]
There was a problem with breakpoint resolution, which I fixed recently. Can you guys try the latest version from the vscode marketplace and let me know if that solves your issues?

**Comment by brikken** [comment]
I still had the test from my original post lying around, so I tried it again. Now it breaks at the breakpoint, but both stepping over (F10) and stepping in (F11) finishes the debugging session and outputs the parse tree to the debug log. If that's a real issue, I'll create a new one.

**Comment by Lufatec** [comment]
hi @mike-lischke, which version this issue was fixed at?
I am still seeing this issue in version v2.2.4.

vscode version is:
Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by mike-lischke** [comment]
@elipersonal Please don't hijack an already closed bug. Usually such bugs (particularly when they are so old) have completely different circumstances to consider, than your current problem Instead, open a new bug. Thanks.

**Comment by elipersonal** [comment]
I am sorry, i am fairly new to this.
will open a new bug instead. thanks again
