### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by YangPatrick** [mike-lischke/vscode-antlr4#75]
- Issue Type: `Performance`
- Extension Name: `vscode-antlr4`
- Extension Version: `2.1.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/user/mike-lischke.vscode-antlr4-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mike-lischke** [comment]
@YangPatrick Can you still reproduce this issue? If so, please attach the mentioned cpuprofile file to this issue. I will then try to identify something that can be improved, but keep also in mind this extension uses Java in the background to run the antlr4 jar for generation of parser + lexer files, which is by nature a bit slow. Furthermore let me know what the specs of your computer are. Slower machines obviously are more exposed to high load than faster ones.
