### ISSUE TITLE
Visitors don't work

### ISSUE THREAD

**Issue by notsonotso** [mike-lischke/vscode-antlr4#8]
https://github.com/antlr/antlr4/issues/1995

The plugin should probably only support generating listeners for now, since the visitor implementation is completely bogus.

**Comment by mike-lischke** [comment]
The plugin doesn't only generate parsers for the Javascript target.

**Comment by notsonotso** [comment]
@mike-lischke good point 😂

**Comment by tvkit** [comment]
To visit Terminals and Errors, you can add the following to the generated listener

```
    visitTerminal(node) {
        console.log(`visited: ${node.getText()}`);
    }

    visitErrorNode(node) {
        console.log(`error: ${node.getText()}`);
    }

```
