### ISSUE TITLE
Debugger fails to load

### ISSUE THREAD

**Issue by jhyry-gcpud** [mike-lischke/vscode-antlr4#80]
![image](https://user-images.githubusercontent.com/30804961/58288622-02970300-7d69-11e9-963d-cd0792bb3f7e.png)

This used to work, and this error tells me nothing.
Here's my launch configuration:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "antlr4-obj-diff",
            "type": "antlr-debug",
            "request": "launch",
            "input": "res/test/input.txt",
            "grammar": "ObjectDiff.g4",
            "startRule": "object_diff",
            "printParseTree": false,
            "visualParseTree": true
        }
    ]
}
```

I have regenerated 10+ times, does nothing to allay this message.

**Comment by mike-lischke** [comment]
Is "ObjectDiff.g4" the correct path to your grammar? What happens when you omit the `grammar` setting and instead open a grammar in the editor and lauch from there?

Please also try the latest release to see if that improves your situation.
