### ISSUE TITLE
Typescript  - Generation

### ISSUE THREAD

**Issue by wagmannj** [mike-lischke/vscode-antlr4#81]
I have some Problems to generate typescript parser/lexer Output. After some Debugging i found the Problem is the using of antlr4-typescript-4.6-SNAPSHOT-complete.jar for code generation. I temporary change it with antlr4-typescript-4.7.2-SNAPSHOT-complete.jar. The generated code ist well, but the ANTLR Plugin is in a loop. 
Please update antlr4-typescript-4.6-SNAPSHOT-complete to a newer version.
Thx Sepp

**Comment by mike-lischke** [comment]
The current code base already uses the antlr4ts version that comes with the antlr4ts npm package. However, I have to publish that finally to make it available.
