### ISSUE TITLE
ActionFile.js example Not working

### ISSUE THREAD

**Issue by mellester** [mike-lischke/vscode-antlr4#82]
I used the example ActionFile.js but vs code tells me. Property actionFile is not allowed in task.json

**Comment by mike-lischke** [comment]
@mellester I don't know which `ActionFile.js` file you mean. There's no such file in the repo. Can you explain in more detail what your problem is?

**Comment by mellester** [comment]
[Grammar-debugging.md](https://github.com/mike-lischke/vscode-antlr4/blob/3f883cbfad4f89775b3193d97ebed268747c1725/doc/grammar-debugging.md#introduction)

```{
    "version": "2.0.0",
    "configurations": [
        {
            "name": "Debug ANTLR4 grammar",
            "type": "antlr-debug",
            "request": "launch",
            "input": "input.txt",
            "grammar": "grammars/Example.g4",
            "actionFile": "grammars/exampleActions.js",
            "startRule": "start",
            "printParseTree": true,
            "visualParseTree": true
        }
    ]
}```

I followed the instructions but the property "Actionfile" is not recognized by my Vscode.
Meaning whatever Actionfile.js I create. Even copying the grammars/exampleActions.js and Example.g4 from the doc. Predicates have no influence on any debug test I run.
I am on windows. 
I tried looking into the packkage.json to see if the property simply was not defined. Or some other setting had to be set. But It seems to be there in the json and I know not enough to help you fix it

**Comment by mike-lischke** [comment]
Unfortunately, this functionality is not yet published, as I'm still working on the grammar sentence generation. You can create a private extension from this repo to get this ability, but you have to add it manually to vscode to make this work.

**Comment by mellester** [comment]
alright I shall try it out.

**Comment by danielgesua** [comment]
Hi Mike,

I'm having the same problem. I wonder if you'd be able to help me.

To be honest I have zero Javascript experience. I copy-pasted the example's code into a JS file on the root, properly added the filename to the "actionFile" field of the launch.json, tried running the debugger, and got an error saying:

"Could not prepare debug session:
 ReferenceError: module is not defined"

Then I tried converting the code to ES6 using VSCode's automatic conversion feature, and that gave me:

"Could not prepare debug session: 
SyntaxError: Unexpected token 'export'"

Then I figured maybe it was cause I didn't have NodeJS installed on this workstation so I tried installing and adding the path to PATH in my environment variables. No luck, same errors.

I tried all the above with both the "PredicateEvaluator" snippet and the "standalone function" snippet and still couldn't get it.

I pray you can help me determine what kind of silly non-sense I'm doing wrong hahaha. 

Without predicates, I wouldn't be able to apply the true power of Antlr4 and this extension has been a game changer thanks to it's amazing graphical representations. 

For reference, I'm running a windows 10 computer, the extension version is 2.2.4.

Thanks for making such an amazing application. I can't wait to see it develop.

Best,

Daniel Gesua

**Comment by mike-lischke** [comment]
Hi Daniel, please open a new issue instead of hijacking this old one. We can then talk there, but my reaction will be slow, since I'm going to travel the next weeks.

**Comment by danielgesua** [comment]
Oh sure! Sorry about that. Enjoy your travels and be careful out there.
