### ISSUE TITLE
C# as output language

### ISSUE THREAD

**Issue by zinov** [mike-lischke/vscode-antlr4#83]
Is there any way to specify C# as the output language of the Lexer and the Parser?

**Comment by mike-lischke** [comment]
Sure, see the parser generation settings: https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/extension-settings.md#parser-generation.

**Comment by zinov** [comment]
do you have an example of how to do it?

**Comment by ronnieoverby** [comment]
Setting language isn't working for me.

![image](https://user-images.githubusercontent.com/101028/62182938-64a25480-b326-11e9-9799-a9ce83d3357d.png)

**Comment by ronnieoverby** [comment]
Nevermind, I've got it sorted out. I needed to specify mode=external and an outputDir:

![image](https://user-images.githubusercontent.com/101028/62183158-04f87900-b327-11e9-81e7-55cdfb64ceeb.png)

**Comment by mike-lischke** [comment]
@ronnieoverby thanks for posting the solution, @zinov does this solve your issue?
