### ISSUE TITLE
Debugger Visualisation dosnt work when no internet

### ISSUE THREAD

**Issue by itgenie98** [mike-lischke/vscode-antlr4#84]
Steps to reproduce:
- Unplug PC from internet
- Hit F5 with the standard debug configuration -> Tree will be parsed but dosnt show up in the visualitation.
- Plug PC back to internet
- Hit F5 again -> Tree visualitaion works as usual.

**Comment by mike-lischke** [comment]
You have to allow it to download D3.js once. After that it should work without internet connection. Maybe it's possible to use the NPM D3.js module with plain JS too?

**Comment by itgenie98** [comment]
I have run it serveral times before with internet connection, but everytime when loosing connection the debugger wont work until the connection is etablished again.

![Screenshot_1](https://user-images.githubusercontent.com/16072267/59688307-b4491880-91dd-11e9-994e-cc16287a498b.png)

![Screenshot_2](https://user-images.githubusercontent.com/16072267/59688332-bdd28080-91dd-11e9-94ab-2027c24d1107.png)

**Comment by mike-lischke** [comment]
@itgenie98 Can you please try with the latest release? I changed the import to use the local node_modules instead of trying to download D3.js from the net.
