### ISSUE TITLE
debugger ignores superClass option of grammars

### ISSUE THREAD

**Issue by itgenie98** [mike-lischke/vscode-antlr4#85]
Currently it seems that the debugger completly ignores the option for lexer and parser superclasses.

```
grammar Test;

option {
    superClass=MyParserSuper;
}

...
```

Superclasses are supported by antlr4: https://github.com/antlr/antlr4/blob/master/doc/options.md#grammar-options , and also by antlr4ts.

**Comment by mike-lischke** [comment]
The debugger uses the interpreter (as is [explained in the docs](https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/grammar-debugging.md)). A base (or super) class only makes sense if you instantiate a lexer or parser.
