### ISSUE TITLE
The file generation call should not use parameters for values that have not been given in the settings

### ISSUE THREAD

**Issue by Thaina** [mike-lischke/vscode-antlr4#89]
![image](https://user-images.githubusercontent.com/1042507/63419382-e9b4f100-c42e-11e9-9a61-7cc96b57d77c.png)

I expect it should output a cs file. But it actually came out java

And actually I think options in the file should take more precedence, is it any reason not to?

**Comment by mike-lischke** [comment]
No, command line parameters have higher precedence and the extension uses such parameters to guide the generation.

However, it should be possible not to specify an option on the command line if no value is given for it in the generation settings. That way it would use defaults or (like in this case) settings from the grammar itself.

**Comment by Thaina** [comment]
@mike-lischke I think there was another approach I would like it to be

Could we let `outputDir` still work on `internal` mode?
What I actually want is just specify language in `g` file and output it into some directory. I use `external` mode just because `outputDir` don't work in internal

**Comment by mike-lischke** [comment]
But the main aspect of an internal build is to hide the generated files! If we would allow to specify a custom output folder, we could as well just remove the internal build mode.

I also wonder how that would help you, since even in internal mode a target language etc. is specified. It's no different to the external mode.

**Comment by Thaina** [comment]
@mike-lischke I see. I actually don't know much detail about this tools. It just work for me to generate DSL parser. Thank you

**Comment by Thaina** [comment]
@mike-lischke Should we have this option though?

> However, it should be possible not to specify an option on the command line if no value is given for it in the generation settings. That way it would use defaults or (like in this case) settings from the grammar itself.

**Comment by mike-lischke** [comment]
Sure, we can convert that question to a feature request.

**Comment by mike-lischke** [comment]
I just checked this report and cannot see any issue here. It was always so that, when you don't specify a language in the settings, no language parameter was sent to the antlr4 jar. Hence the jar decided what to generate, either the default (Java) or what was set in the grammar.
