### ISSUE TITLE
How can I disable or format the "Generated from" comment in antlr

### ISSUE THREAD

**Issue by Thaina** [mike-lischke/vscode-antlr4#90]
I don't want it to show a full path

```C#
// Generated from c:\Users\Thaina\Documents\grownith\NCalc2\grammer\NCalc.g4 by ANTLR 4.7.1
```

Not to mention it always annoying when changing machine and recompile g file, it will change this line. Why it is fullpath when it actually should be relative path?

**Comment by mike-lischke** [comment]
This is a comment generated by ANTLR4, not the vscode extension. You will get this also when you manually execute the ANTLR4 jar file.

**Comment by Thaina** [comment]
@mike-lischke I was suspect that too but also I had investigated that people can generate that comment as relative path using antlr

Which make me also suspect that maybe it might caused from the extension send full path as an argument? Or it should have set some option in antlr argument? I'm not sure

**Comment by mike-lischke** [comment]
I'm afraid that's not possible with reasonable effort. The file names are stored in the managing source contexts for each grammar file and the corresponding can be anywhere on the file system. There's nothing like an ANTLR4 project format to group files, so I have to use other means to identify the input files correctly, which is best/easiest done by using an absolute path. I'm afraid the best option you have is to manually remove the path from the generated files.

**Comment by Thaina** [comment]
There was a response from the antlr repo that the official version had fix this

https://github.com/antlr/antlr4/issues/2634

**Comment by Thaina** [comment]
@mike-lischke Any updates?

**Comment by mike-lischke** [comment]
I explained already that it is impossible to change this additional info. The extension has to use absolute paths and the ANTLR4 tool always includes this line.

**Comment by Thaina** [comment]
@mike-lischke I think by this comment, https://github.com/antlr/antlr4/issues/2634#issuecomment-540805323 it possible to use relative path for antlr. Could you please give me some clue why it not possible for this extension to use antlr with relative path?

**Comment by mike-lischke** [comment]
I mentioned that already. The extension can manage grammars from all disk paths and the grammar path is the unique key to find it, even with multiple same-named grammars. And since there's not enough demand to use relative paths I will not change the implementation.
