### ISSUE TITLE
Error while launching debug session: start rule "tune" not found

### ISSUE THREAD

**Issue by Andis59** [mike-lischke/vscode-antlr4#93]
I'm a beginner of **Antlr4** and of **vscod-antlr4**. 
I have configured a launch setting for my grammar, but when I run it I get the error that the start rule is not found!
This is my launch configuration:
```
"version": "2.0.0",
    "configurations": [
        {
            "type": "antlr-debug",
            "request": "launch",
            "name": "Debug current Grammar",
            "input": "JingleBellsLow.simple",
            "startRule": "tune",
            "printParseTree": true,
            "visualParseTree": true,
            "trace": true
        }
    ]
```
This is an extract of the Simple.g4 file
```
grammar Simple;

// parser rules

tune : header music+ EOF;
```
[Simple.zip](https://github.com/mike-lischke/vscode-antlr4/files/3597790/Simple.zip)

So the rule is there (?)

I get this trace:

> From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"antlr-debug","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"})
> To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsStepInTargetsRequest":true}}
> To client: {"seq":0,"type":"event","event":"initialized"}
> From client: setExceptionBreakpoints({"filters":[]})
> To client: {"seq":0,"type":"response","request_seq":2,"command":"setExceptionBreakpoints","success":true}
> From client: launch({"type":"antlr-debug","request":"launch","name":"Debug current Grammar","input":"C:\\Users\\Anders\\Source\\Repos\\SimpleNotation\\AntlrConsole1\\JingleBellsLow.simple","startRule":"tune","printParseTree":true,"visualParseTree":true,"trace":true,"grammar":"c:\\Users\\Anders\\Source\\Repos\\SimpleNotation\\AntlrConsole1\\Simple.g4","debugServer":62896,"__sessionId":"1248b4c4-f826-408d-bd7f-f992eeb98fc6"})
> From client: configurationDone(undefined)
> To client: {"seq":0,"type":"response","request_seq":4,"command":"configurationDone","success":true}
> To client: {"seq":0,"type":"response","request_seq":3,"command":"launch","success":false,"message":"Error while launching debug session: start rule \"tune\" not found","body":{"error":{"id":1,"format":"Error while launching debug session: start rule \"tune\" not found"}}}

What have I done wrong?
// Anders
**VSCode**
Version: 1.38.0 (user setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**vscode-antlr4** 
version 2.1.1

**Comment by mike-lischke** [comment]
You have not specified a grammar rule name in your launch config. So when you start debugging the currently active grammar is used instead. Does this grammar really contain the mentioned start rule? Try also a different rule instead.

**Comment by mike-lischke** [comment]
Please try the latest release of the extension. I cannot reproduce the issue:

<img width="2089" alt="Simple" src="https://user-images.githubusercontent.com/2398704/69237799-c23d0400-0b96-11ea-9a16-bbb860aef662.png">
