### ISSUE TITLE
Support for multiple importdirs

### ISSUE THREAD

**Issue by rgiacomin** [mike-lischke/vscode-antlr4#98]
It seems that it is not possible to set multiple import directories. Am I missing anything? Is there any workaround?

**Comment by mike-lischke** [comment]
ANTLR4 doesn't support more than a [single lib](https://github.com/antlr/antlr4/blob/master/doc/tool-options.md#-lib-libdir) dir (which is used for the import directory setting in this extension). So, I'm afraid, I can't implement this feature request.
