### ISSUE TITLE
VS Code crashes when debugging nested rules

### ISSUE THREAD

**Issue by dspickes** [mike-lischke/vscode-antlr4#99]
VS Code is crashing on my Win10 machine when debugging an ANTLR parse tree that nests more than 11 levels deep. I was concerned that I only noticed this issue begin within the last few weeks. So I checked, and VS Code crashes when I target both the 2.1.1 and 2.2.3 versions of the extension. [Here](https://github.com/mike-lischke/vscode-antlr4/files/3884244/antlr-bug-info.zip) is a minimal example of the ANTLR grammar and input which causes the crash, as well as the native crash logs obtained by following [these instructions](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues). I don't know how relevant this is, but I found the Win32 error codes 0X406D1388 and 0X0000071A when investigating the crash logs.

This extension is incredible, and I love using it. Any help trying to understand or resolve this issue would be greatly appreciated.

**Comment by dspickes** [comment]
UPDATE: turning off the visual parse tree in launch.json prevents the crash. The print parse tree setting does not appear to have any effect on the crash. Also, running VS Code as administrator does not seem to have any effect on the crash.

**Comment by mike-lischke** [comment]
I just tested this with my latest code on Win 10 and everything looked fine. So maybe this has been fixed by other code changes meanwhile?

I will soon post a new release for this extension. Please test this once it is out and report your findings here.
